import { existsSync, readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { describe,expect,it } from 'vitest'
import { CitadelNetworkGame, CommandResonanceGame, ElaraShuttleEscapeGame, EndingChoiceGame, OccupationEvidenceGame, SharedMemoryGame, ShipyardInfiltrationGame, endingEligibility, evidenceOutcome, infiltrationOutcome, memoryBridgeOutcome, networkOutcome, resonanceOutcome, shuttleOutcome } from '../src/slice/ActFourGames.js'
import { ACT_FOUR_INTERLUDES, elaraIntroductionScene, eliasRecognitionScene, fatherDaughterScene, finalContactScene, gateTruthScene } from '../src/slice/actFourContent.js'
import { citadelCombatConfig, finalCombatConfig } from '../src/slice/SliceGame.js'
import { combatObjectiveComplete, type LiveCombatTarget } from '../src/slice/CinematicCombat.js'
import { createInitialState } from '../src/state/initial.js'
import type { GameState } from '../src/state/types.js'

type GamePatch=Omit<Partial<GameState>,'relationships'|'characters'>&{relationships?:Partial<GameState['relationships']>;characters?:Partial<GameState['characters']>}
function stateWith(patch:GamePatch):GameState{const base=createInitialState('act-four-adversary');return{...base,...patch,relationships:{...base.relationships,...patch.relationships},characters:{...base.characters,...patch.characters},ship:patch.ship??base.ship}}

describe('complete Act IV adversarial release gate',()=>{
 it('renders every new interaction with a concrete objective and visible state',()=>{const game=stateWith({flags:['tide-gate-crime-exposed'],evidence:['phaeacian-account:8:4:5','memory-bridge:3']});const noop=()=>undefined;for(const node of [createElement(OccupationEvidenceGame,{onComplete:noop}),createElement(ElaraShuttleEscapeGame,{onComplete:noop}),createElement(ShipyardInfiltrationGame,{onComplete:noop}),createElement(CommandResonanceGame,{onComplete:noop}),createElement(CitadelNetworkGame,{onComplete:noop}),createElement(SharedMemoryGame,{onComplete:noop}),createElement(EndingChoiceGame,{game,onComplete:noop})]){const html=renderToStaticMarkup(node);expect(html).toContain('OBJECTIVE');expect(html.length).toBeGreaterThan(700)}})
 it('makes Elara investigate independent evidence before trusting identity',()=>{expect(evidenceOutcome(['phaeacian-witness','evacuation-hash','unflattering-ledger'])).toMatchObject({correct:3,success:true});expect(evidenceOutcome(['heroic-codes','recent-patrols','perfect-biometric'])).toMatchObject({correct:0,success:false});expect(elaraIntroductionScene(createInitialState()).lines.map(l=>l.text).join(' ')).toContain('who profits')})
 it('keeps chase and infiltration fail-forward with legible persistent costs',()=>{expect(shuttleOutcome(['freight-shadow','cold-roll','split-key'])).toMatchObject({mistakes:0,hullDamage:0,success:true});expect(shuttleOutcome(['patrol-gap','counterfire','broadcast-name'])).toMatchObject({mistakes:3,hullDamage:15,success:false});expect(infiltrationOutcome(['freight-lift','manual-sequence','old-gesture'])).toMatchObject({alert:0,success:true});expect(infiltrationOutcome(['command-door','voiceprint','rank-code'])).toMatchObject({alert:3,success:false})})
 it('separates private recognition, authentication and moral authority',()=>{const game=stateWith({evidence:['occupation-evidence:3','last-companion:lena-mori']});expect(eliasRecognitionScene(game).lines.map(l=>l.text).join(' ')).toContain('not an authentication task');expect(fatherDaughterScene(game).choices?.map(c=>c.id)).toEqual(['ask-elara-to-judge','surrender-command-codes','reclaim-command']);expect(resonanceOutcome(['scar-history','contradiction','public-record'])).toMatchObject({correct:3,success:true});expect(gateTruthScene(game).title).toContain('cradle')})
 it('never resurrects the dead companion as live trial testimony',()=>{const game=stateWith({evidence:['last-companion:helen-morozova'],characters:{'helen-morozova':{status:'dead',injuries:[]}}});const trial=gateTruthScene(game);expect(trial.lines.some(l=>l.speaker==='helen-morozova')).toBe(false);expect(trial.lines.map(l=>l.text).join(' ')).toContain('Both facts')})
 it('protects identity records, civilians and public witnesses in both final battles',()=>{for(const config of [citadelCombatConfig(stateWith({evidence:['shipyard-alert:2']})),finalCombatConfig(stateWith({evidence:['phaeacian-account:8:4:5']}))]){expect(config.targets.filter(t=>t.protected).length).toBeGreaterThanOrEqual(2);const live=config.targets.map(t=>({...t,currentHp:t.protected?t.hp:0})) as LiveCombatTarget[];expect(combatObjectiveComplete(live,config.mode)).toBe(true)}})
 it('makes Elara restore accountable systems before the memory confrontation',()=>{expect(networkOutcome(['phaeacian-buffer','split-ledger','elara-command'])).toMatchObject({correct:3,success:true});expect(memoryBridgeOutcome(['both-gate','both-pursuit','both-future'])).toMatchObject({bridge:3,success:true});expect(memoryBridgeOutcome(['only-orders','only-grief','erase-host'])).toMatchObject({bridge:0,success:false})})
 it('always permits survival endings while requiring campaign conduct for reconciliation and succession',()=>{const base=stateWith({flags:['tide-gate-crime-exposed'],evidence:['memory-bridge:3']});expect(endingEligibility(base)).toMatchObject({vengeance:true,atonement:true,exile:true,reconciliation:false,succession:false});const earned=stateWith({flags:['tide-gate-crime-exposed','phaeacians-told-truth','helios-remnant-preserved','elara-trusts-vale'],evidence:['memory-bridge:3'],relationships:{'elara-vale':3}});expect(endingEligibility(earned)).toMatchObject({vengeance:true,atonement:true,reconciliation:true,exile:true,succession:true})})
 it('paces every final beat with causal context, character pressure and delayed choice',()=>{for(const interlude of Object.values(ACT_FOUR_INTERLUDES)){expect(interlude.recap.length).toBeGreaterThan(220);expect(interlude.situation).toHaveLength(3);expect(interlude.objective.length).toBeGreaterThan(100)}const game=stateWith({evidence:['memory-bridge:3','occupation-evidence:3']});for(const scene of [elaraIntroductionScene(game),eliasRecognitionScene(game),fatherDaughterScene(game),gateTruthScene(game),finalContactScene(game)])expect(scene.lines).toHaveLength(6)})
 it('ships six distinct cinematic frames with laptop-height and reduced-motion composition',()=>{for(const name of ['earth-shipyard.webp','shipyard-recognition.webp','command-citadel.webp','earth-orbit-siege.webp','shared-memory.webp','earth-epilogue.webp']){const file=join(process.cwd(),'public/assets/cinematics',name);expect(existsSync(file)).toBe(true);expect(statSync(file).size).toBeGreaterThan(75_000)}const css=readFileSync(join(process.cwd(),'src/ui/styles.css'),'utf8');expect(css).toContain('@media(max-height:850px) and (min-width:801px)');expect(css).toContain('@media(prefers-reduced-motion:reduce)')})
})
