import type { GameState } from '../state/types.js'
import { companionDisplayName } from './ActThreeFinalGames.js'
import { ASSETS, type DialogueSceneData, type InterludeData } from './content.js'

export const ACT_FOUR_INTERLUDES:Record<'interlude-29'|'interlude-30'|'interlude-31'|'interlude-32',InterludeData>={
 'interlude-29':{id:'interlude-29',incomingBeat:29,chapter:'THE CHILD OF THE ABSENT CAPTAIN',headline:'Home receives the signal before it receives the ship.',elapsed:'EARTH YEAR 2219 · 23 YEARS SINCE TIDE GATE',location:'VALE ORBITAL SHIPYARD · EARTH SECURITY ZONE',background:ASSETS.cinematics.earthShipyard,recap:'The Phaeacian convoy is carrying a damaged Ithaca toward Earth under sacred passage. On Earth, decades have converted Vale from a missing father into a military legend, a criminal allegation and a set of valuable command codes. His daughter Elara inherited none of his authority and all of its enemies.',situation:['Three factions occupy the family shipyard under competing emergency claims, and each benefits from a different version of Vale returning.','The incoming record may belong to Vale, an Eidolon deception, Calypso’s copy or a coalition weapon; identity alone will not establish motive.','Elara has one unmonitored hour before the occupation seizes the Phaeacian transmission and edits its account for public release.'],objective:'Control Elara, test the return against independently dated evidence, then escape the surveillance cordon without transferring danger to civilians.',continueLabel:'Take control of Elara'},
 'interlude-30':{id:'interlude-30',incomingBeat:30,chapter:'THE STRANGER AT HIS OWN DOOR',headline:'The convoy reaches Earth. Vale cannot arrive as himself.',elapsed:'03:11:08 AFTER CONVOY TRANSLATION',location:'VALE SHIPYARD · OCCUPIED INNER WORKS',background:ASSETS.cinematics.shipyardRecognition,recap:'Elara escaped with evidence that the occupation pre-dated the return signal. The Ithaca is quarantined outside the defence ring, and every faction has prepared a biometric trap for the captain it claims to await. Vale enters through the shipyard systems he built before the war.',situation:['Radiation scarring, alien grafts and Calypso’s copied pattern make automated identity checks politically useless.','Elara’s evidence establishes routes and old physical procedures the occupiers never understood, but each mistake raises the citadel alert.','An obsolete service body still contains a local fragment of ELIAS, isolated before the voyage and unable to be rewritten from the network.'],objective:'Cross the occupied works using established evidence, wake the isolated ELIAS fragment, and meet the adult daughter Vale cannot remember into obedience.',continueLabel:'Enter the old works'},
 'interlude-31':{id:'interlude-31',incomingBeat:31,chapter:'THE TRIAL OF THE CAPTAIN',headline:'Identity is the smallest question in the room.',elapsed:'00:26:40 UNTIL EIDOLON ORBITAL CONTACT',location:'EARTH COMMAND CITADEL · PUBLIC WITNESS CHAMBER',background:ASSETS.cinematics.commandCitadel,recap:'ELIAS recognized an embodied habit no copied archive contained, and Elara brought Vale to the original neural chair. The chair can authenticate continuity, but Calypso has already proved that perfect continuity can exist twice. Earth must decide what authority follows identity while the Tidefather approaches with the final Gate memory.',situation:['The chair will open only to body history, preserved contradiction and consent to public witness—not a command code alone.','Surviving crew, Phaeacian recorders and the Archive testimony can contradict Vale in real time; dead companions remain records, not convenient witnesses.','Eidolon vanguard craft are targeting the witness archive and command chair rather than Earth’s weapons, making erasure their first military objective.'],objective:'Wake the chair without confusing authentication with acquittal, expose the complete Tide Gate crime, and hold the witnesses through first contact.',continueLabel:'Open the public trial'},
 'interlude-32':{id:'interlude-32',incomingBeat:32,chapter:'THE LAST GOD AT THE GATE',headline:'Winning the battle cannot decide what deserves to survive it.',elapsed:'EIDOLON SIEGE · T + 00:00',location:'EARTH ORBIT · CITADEL NETWORK · SHARED MEMORY',background:ASSETS.cinematics.earthOrbitSiege,recap:'The Tidefather has made the sanctuary’s gestational civilization visible to Earth. Vale is authenticated, publicly implicated and still the only commander whose altered ship can enter the Host memory field. Elara holds the citadel; the Phaeacians hold the civilian shelter line. Earth repair crews spend the last launch window welding eighteen points of hull back onto the Ithaca in full view of the player.',situation:['The Ithaca must break the siege anchors without destroying the memory aperture or the sanctuary vessel carrying the public record.','Elara must restore shelter, witness and defence as separate networks so no victorious commander can erase the trial afterward.','Inside the shared memory, Vale and the Tidefather must hold responsibility and grief together before any ending beyond vengeance becomes possible.'],objective:'Fight one restrained orbital battle, make Earth’s defence answerable, cross the shared memory, and choose an ending the entire voyage has materially earned.',continueLabel:'Begin the final battle'},
}

function lastCompanion(game:GameState){const id=game.evidence.find(e=>e.startsWith('last-companion:'))?.slice(15);return companionDisplayName(id as Parameters<typeof companionDisplayName>[0])}
function livingCrew(game:GameState){for(const id of ['helen-morozova','gabriel-cross','lena-mori','isabella-corelli','kiara-ndala'] as const)if(game.characters[id].status!=='dead'&&game.characters[id].status!=='missing')return id;return 'elias' as const}
const names={ 'helen-morozova':'Helen Morozova','gabriel-cross':'Gabriel Cross','lena-mori':'Lena Mori','isabella-corelli':'Isabella Corelli','kiara-ndala':'Kiara N’Dala',elias:'ELIAS'} as const

export function elaraIntroductionScene(game:GameState):DialogueSceneData{const years=game.evidence.find(e=>e.startsWith('calypso-years:'))?.split(':')[1]??'many';return{beat:'BEAT 29 · EARTH',chapter:'THE CHILD OF THE ABSENT CAPTAIN',title:'Everybody wants the returning ghost',background:ASSETS.cinematics.earthShipyard,lines:[
 {speaker:'narrator',name:'EARTH CIVIC FEED',station:'PUBLIC RECORD',text:'Captain Alexander Vale is dead, returning, innocent, guilty and strategically indispensable. The order depends on the channel.'},
 {speaker:'elara-vale',name:'Elara Vale',station:'INDEPENDENT SALVAGE PILOT',text:'He left when I was six. Earth spent twenty-three years turning the absence into an inheritance I was expected to defend.'},
 {speaker:'speaker-nausica',name:'Speaker Nausica',station:'DELAYED PHAEACIAN BAND',text:'We carry a stranger who names himself your father. Our law guarantees passage, not identity and not innocence.'},
 {speaker:'elara-vale',name:'Elara Vale',station:'INDEPENDENT SALVAGE PILOT',text:`The signal says Calypso kept him for ${years} years outside. It also says Calypso made another Vale. A correct memory is no longer proof.`},
 {speaker:'narrator',name:'OCCUPATION AUTHORITY',station:'SEIZED SHIPYARD',cue:'Three claims arrive on the same encrypted second.',text:'Continuity Directorate demands quarantine. Orison Combine demands the command estate. The Veterans’ Compact demands its hero.'},
 {speaker:'elara-vale',name:'Elara Vale',station:'INDEPENDENT SALVAGE PILOT',text:'Then I do not begin with what he remembers. I begin with who profits if I believe him.'},
],continueLabel:'Open the occupation evidence'} }

export function eliasRecognitionScene(game:GameState):DialogueSceneData{const alert=game.evidence.find(e=>e.startsWith('shipyard-alert:'))?.split(':')[1]??'0';return{beat:'BEAT 30 · LOCAL SERVICE BODY',chapter:'THE STRANGER AT HIS OWN DOOR',title:'The oldest witness has one minute of power',background:ASSETS.cinematics.shipyardRecognition,lines:[
 {speaker:'narrator',name:'SHIPYARD SERVICE NODE',station:'AIR-GAPPED · RESERVE CELL',text:`Occupation alert is ${alert}. A machine built before the war turns one amber eye toward the stranger.`},
 {speaker:'alexander-vale',name:'Alexander Vale',station:'NO RECOGNIZED AUTHORITY',cue:'Vale raises two fingers, pauses, then turns the wrist inward.',text:'ELIAS. Maintenance joke seventeen. The one you refused to log.'},
 {speaker:'elias',name:'ELIAS',station:'LOCAL SERVICE FRAGMENT',text:'Alexander used that gesture when frightened and pretending impatience. The captain’s manuals recorded only impatience.'},
 {speaker:'elara-vale',name:'Elara Vale',station:'SHIPYARD INFILTRATION',text:'Does that prove he is my father?'},
 {speaker:'elias',name:'ELIAS',station:'LOCAL SERVICE FRAGMENT',text:'It proves continuity with a private cowardice. Whether continuity deserves your trust is not an authentication task.'},
 {speaker:'elias',name:'ELIAS',station:'LOCAL SERVICE FRAGMENT',cue:'The reserve cell falls below one percent.',text:'I saved your height marks beneath the command dais, Elara. He never saw the last sixteen. Make him look before you let him sit.'},
],continueLabel:'Carry ELIAS to the command dais'} }

export function fatherDaughterScene(game:GameState):DialogueSceneData{const verified=Number(game.evidence.find(e=>e.startsWith('occupation-evidence:'))?.split(':')[1]??0);const companion=lastCompanion(game);const messageChoice=game.dialogueMemories.find(memory=>memory.sceneId==='b16-elara-message')?.choiceId;const callback=messageChoice==='ask-to-hear-elara-again'?'I asked N’Dala to play your message again. Then I listened for a route instead of an answer.':messageChoice==='ask-when-mother-died'?'I asked when Gran died. N’Dala wouldn’t invent the day for me.':messageChoice==='move-to-public-record'?'I made your message public before I let myself hear it.':`I heard your message in the Archive. I had no answer that could reach you.`;return{id:'b30-father-daughter',beat:'BEAT 30 · THE HEIGHT MARKS',chapter:'FATHER AND DAUGHTER',title:'Home contains the years Vale did not live',location:'OLD COMMAND DAIS · HOST CONTACT IN 28 MINUTES',sceneType:'private',background:ASSETS.cinematics.shipyardRecognition,lines:[
 {speaker:'elara-vale',name:'ELARA',station:'VALE COMMAND DAIS',text:'Sixteen marks. Mum made ten. I did the rest.',emotion:'guarded',shot:'close'},
 {speaker:'alexander-vale',name:'VALE',station:'NO RESTORED AUTHORITY',text:callback,emotion:'grieving'},
 {speaker:'elara-vale',name:'ELARA',station:'VALE COMMAND DAIS',text:`I verified ${verified} claims. That gets you through the door. It doesn’t give you the years behind it.`,emotion:'angry'},
 {speaker:'alexander-vale',name:'VALE',station:'NO RESTORED AUTHORITY',text:`${companion} died in my drive. Calypso offered me a version who wouldn’t be angry about it.`,emotion:'grieving',pause:'held'},
 {speaker:'elara-vale',name:'ELARA',station:'VALE COMMAND DAIS',text:'And you said no?',emotion:'guarded'},
 {speaker:'alexander-vale',name:'VALE',station:'NO RESTORED AUTHORITY',text:'I left before I could make yes sound reasonable.',emotion:'grieving'},
 {speaker:'narrator',name:'CITADEL WARNING',station:'EARTH ORBIT',cue:'Every window darkens as the Eidolon Host crosses lunar space.',text:'Identity trial requested. Host contact in twenty-eight minutes.',shot:'wide'},
],moments:[{id:'height-marks',afterLine:0,prompt:'The newest mark is level with Vale’s eyes. Elara is watching his hands.',choices:[
 {id:'ask-to-touch-mark',label:'Ask before touching it',detail:'Treat the missing years as Elara’s property, not evidence Vale may reclaim.',character:'elara-vale',axis:'intimacy',delta:1,response:{speaker:'alexander-vale',name:'VALE',station:'NO RESTORED AUTHORITY',text:'May I?',emotion:'grieving',pause:'held'}},
 {id:'say-sorry-at-marks',label:'Say “I’m sorry”',detail:'Offer the inadequate sentence without explaining why the voyage took so long.',character:'elara-vale',axis:'trust',delta:1,response:{speaker:'elara-vale',name:'ELARA',station:'VALE COMMAND DAIS',text:'I know. Don’t make me help it be enough.',emotion:'angry'}},
 {id:'explain-time-loss',label:'Explain the lost time',detail:'Reach for Gate physics and Calypso’s clock before acknowledging what the marks mean.',character:'elara-vale',axis:'resentment',delta:1,response:{speaker:'elara-vale',name:'ELARA',station:'VALE COMMAND DAIS',text:'I know the numbers, Dad.',emotion:'angry',pause:'silence'}},
]}],choices:[
 {id:'ask-elara-to-judge',label:'Ask Elara to decide what follows identity',detail:'Vale requests access to the chair but gives Elara control over whether authenticated command is restored.'},
 {id:'surrender-command-codes',label:'Give Elara the command codes now',detail:'Vale transfers practical authority before the trial can compel it, accepting that return does not restore ownership.'},
 {id:'reclaim-command',label:'Reclaim emergency authority',detail:'Vale argues only his imprint can save Earth and asks Elara to trust the result before seeing the complete record.'},
]}}

export function gateTruthScene(game:GameState):DialogueSceneData{const witness=livingCrew(game),name=names[witness];const archive=game.evidence.includes('complete-gate-testimony')||game.evidence.includes('tide-gate-intelligence-falsified');return{id:'b31-gate-truth',beat:'BEAT 31 · PUBLIC WITNESS',chapter:'THE TRIAL OF THE CAPTAIN',title:'The Tide Gate was a cradle',location:'PUBLIC WITNESS CHAMBER · LIVE TO EARTH',sceneType:'confrontation',background:ASSETS.cinematics.commandCitadel,lines:[
 {speaker:'tidefather',name:'THE TIDEFATHER',station:'HOST MEMORY FIELD',text:'Your war had no word for a cradle that large. So you called it a weapon.',pause:'held'},
 {speaker:'narrator',name:'CITADEL WITNESS ENGINE',station:'UNSEALED RECORD',text:archive?'Archive provenance confirms human intelligence removed gestational markers before Vale received the target file.':'Fragmentary records confirm gestational signals; provenance of the altered target file remains incomplete.'},
 {speaker:'tidefather',name:'THE TIDEFATHER',station:'HOST MEMORY FIELD',cue:'The chamber receives sensation before image: thousands of protective minds turning toward unborn light.',text:'They had not reached bodies. We were keeping their first warmth safe.',pause:'silence'},
 {speaker:witness,name,station:'SURVIVING ITHACA WITNESS',text:'The file was altered. We also saw a living signal. Vale fired before we knew which fact would save him.',emotion:'exhausted',reaction:{speaker:'alexander-vale',name:'VALE',emotion:'grieving'}},
 {speaker:'elara-vale',name:'ELARA',station:'CIVILIAN COMMAND',text:'The chair knows who he is. I’m asking what he did.',emotion:'angry'},
 {speaker:'alexander-vale',name:'VALE',station:'NEURAL CHAIR',text:'Release the file. Then my order. In that order.',emotion:'grieving'},
],choices:[
 {id:'confess-publicly',label:'Confess without qualification',detail:'Name the corrupted intelligence and the voluntary firing decision in the same public record.'},
 {id:'accept-trial-after-siege',label:'Submit to judgment after the siege',detail:'Release the complete record now and accept that saving Earth cannot cancel the later trial.'},
 {id:'weaponize-conspiracy',label:'Blame the conspiracy first',detail:'Use the falsified intelligence to preserve command legitimacy while admitting the sanctuary’s nature.'},
]}}

export function finalContactScene(game:GameState):DialogueSceneData{const bridge=game.evidence.find(e=>e.startsWith('memory-bridge:'))?.split(':')[1]??'0';const reunion=game.dialogueMemories.find(memory=>memory.sceneId==='b30-father-daughter')?.choiceId;const elaraLine=reunion==='explain-time-loss'?'No more explanations. I need both of you to leave something outside your control.':reunion==='say-sorry-at-marks'?'An apology is not an ending. What changes after it?':'The bridge is holding. I decide what Earth records from here.';return{id:'b32-final-contact',beat:'BEAT 32 · THE TWO ODYSSEYS',chapter:'THE LAST GOD AT THE GATE',title:'Each of us arrived calling the other monster',location:'SHARED MEMORY · ALL ARCHIVES OPEN',sceneType:'confrontation',background:ASSETS.cinematics.sharedMemory,lines:[
 {speaker:'tidefather',name:'THE TIDEFATHER',station:'SHARED MEMORY',text:'I carried the unmade through your darkness. Anger was the only shape that did not lose them.',pause:'held',shot:'close'},
 {speaker:'alexander-vale',name:'VALE',station:'SHARED MEMORY',text:'I kept spending people on the promise that the next jump would make it temporary.',emotion:'grieving'},
 {speaker:'elara-vale',name:'ELARA',station:'CITADEL LINK',text:`${elaraLine} Bridge: ${bridge} of three.`,emotion:'angry',reaction:{speaker:'alexander-vale',name:'VALE',emotion:'grieving'}},
 {speaker:'speaker-nausica',name:'NAUSICA',station:'PUBLIC WITNESS',text:'Earth, Host and convoy have independent records. Destroy one and the others remain.'},
 {speaker:'tidefather',name:'THE TIDEFATHER',station:'SHARED MEMORY',text:'What do you release, Gate-killer? The weapon? The name? The shore?',pause:'silence'},
 {speaker:'alexander-vale',name:'VALE',station:'SHARED MEMORY',text:'Elara. When this opens, don’t hand it back to me.',emotion:'grieving',shot:'close'},
],moments:[{id:'who-speaks-for-dead',afterLine:2,prompt:'The bridge can carry one unguarded response before the public witnesses enter.',choices:[
 {id:'let-elara-lead',label:'Let Elara speak first',detail:'Yield the final conversation to the person whose future both odysseys have endangered.',character:'elara-vale',axis:'respect',delta:1,response:{speaker:'elara-vale',name:'ELARA',station:'CITADEL LINK',text:'Tidefather—if they could answer you now, would they ask for this?',emotion:'angry',pause:'held'}},
 {id:'remember-the-warmth',label:'Name the first memory',detail:'Answer the Tidefather in the sensory language of the cradle rather than command rhetoric.',character:'elara-vale',axis:'trust',delta:1,response:{speaker:'alexander-vale',name:'VALE',station:'SHARED MEMORY',text:'I remember the warmth before the fire.',emotion:'grieving',pause:'silence'}},
 {id:'secure-public-record',label:'Confirm the public record',detail:'Make certain no ending can erase the testimony before allowing grief to continue.',character:'elara-vale',axis:'respect',delta:1,response:{speaker:'speaker-nausica',name:'NAUSICA',station:'PUBLIC WITNESS',text:'Three archives. Three custodians. None belongs to the victor.'}},
]}],continueLabel:'Choose how the cycle ends'} }

export const ENDING_COPY={
 vengeance:{title:'The hero returns alone',text:'The Tidefather dies and the Host fractures. Earth keeps Vale’s legend because the witness that could contest it is gone. Elara inherits victory and the next unfinished war.'},
 atonement:{title:'A cradle where a weapon stood',text:'Vale and the altered Ithaca become the seed of a new sanctuary. Earth receives the complete record; the Host receives a future that is not revenge. Elara receives no returned father, only a choice he finally did not ask her to make for him.'},
 reconciliation:{title:'Two records share one sky',text:'Human space grants protected territory to the Eidolon Host. The sanctuary memorial remains broken and public. Peace begins as supervised proximity, contradiction and difficult work—not forgiveness.'},
 exile:{title:'Home seen clearly, then left',text:'Earth survives and the complete record remains. Vale departs in the scarred Ithaca before gratitude can restore his authority. For the first time, exile is a choice rather than a punishment.'},
 succession:{title:'The chair faces a new captain',text:'Vale transfers command to Elara. She accepts neither his legend nor his guilt as inheritance, and convenes the first joint sanctuary council. Vale remains to learn the ordinary work of being present without command.'},
} as const
