import type { GameState } from '../state/types.js'
import { companionDisplayName } from './ActThreeFinalGames.js'
import { ASSETS, type DialogueSceneData, type InterludeData } from './content.js'

export const ACT_FOUR_INTERLUDES:Record<'interlude-29'|'interlude-30'|'interlude-31'|'interlude-32',InterludeData>={
 'interlude-29':{id:'interlude-29',incomingBeat:29,chapter:'THE CHILD OF THE ABSENT CAPTAIN',headline:'Home receives the signal before it receives the ship.',elapsed:'EARTH YEAR 2219 · 23 YEARS SINCE TIDE GATE',location:'VALE ORBITAL SHIPYARD · EARTH SECURITY ZONE',background:ASSETS.cinematics.earthShipyard,recap:'The Phaeacian convoy is carrying a damaged Ithaca toward Earth under sacred passage. On Earth, decades have converted Vale from a missing father into a military legend, a criminal allegation and a set of valuable command codes. His daughter Elara inherited none of his authority and all of its enemies.',situation:['Three factions occupy the family shipyard under competing emergency claims, and each benefits from a different version of Vale returning.','The incoming record may belong to Vale, an Eidolon deception, Calypso’s copy or a coalition weapon; identity alone will not establish motive.','Elara has one unmonitored hour before the occupation seizes the Phaeacian transmission and edits its account for public release.'],objective:'Control Elara, test the return against independently dated evidence, then escape the surveillance cordon without transferring danger to civilians.',continueLabel:'Take control of Elara'},
 'interlude-30':{id:'interlude-30',incomingBeat:30,chapter:'THE STRANGER AT HIS OWN DOOR',headline:'The convoy reaches Earth. Vale cannot arrive as himself.',elapsed:'03:11:08 AFTER CONVOY TRANSLATION',location:'VALE SHIPYARD · OCCUPIED INNER WORKS',background:ASSETS.cinematics.shipyardRecognition,recap:'Elara escaped with evidence that the occupation pre-dated the return signal. The Ithaca is quarantined outside the defence ring, and every faction has prepared a biometric trap for the captain it claims to await. Vale enters through the shipyard systems he built before the war.',situation:['Radiation scarring, alien grafts and Calypso’s copied pattern make automated identity checks politically useless.','Elara’s evidence establishes routes and old physical procedures the occupiers never understood, but each mistake raises the citadel alert.','An obsolete service body still contains a local fragment of ELIAS, isolated before the voyage and unable to be rewritten from the network.'],objective:'Cross the occupied works using established evidence, wake the isolated ELIAS fragment, and meet the adult daughter Vale cannot remember into obedience.',continueLabel:'Enter the old works'},
 'interlude-31':{id:'interlude-31',incomingBeat:31,chapter:'THE TRIAL OF THE CAPTAIN',headline:'Identity is the smallest question in the room.',elapsed:'00:26:40 UNTIL EIDOLON ORBITAL CONTACT',location:'EARTH COMMAND CITADEL · PUBLIC WITNESS CHAMBER',background:ASSETS.cinematics.commandCitadel,recap:'ELIAS recognized an embodied habit no copied archive contained, and Elara brought Vale to the original neural chair. The chair can authenticate continuity, but Calypso has already proved that perfect continuity can exist twice. Earth must decide what authority follows identity while the Tidefather approaches with the final Gate memory.',situation:['The chair will open only to body history, preserved contradiction and consent to public witness—not a command code alone.','Surviving crew, Phaeacian recorders and the Archive testimony can contradict Vale in real time; dead companions remain records, not convenient witnesses.','Eidolon vanguard craft are targeting the witness archive and command chair rather than Earth’s weapons, making erasure their first military objective.'],objective:'Wake the chair without confusing authentication with acquittal, expose the complete Tide Gate crime, and hold the witnesses through first contact.',continueLabel:'Open the public trial'},
 'interlude-32':{id:'interlude-32',incomingBeat:32,chapter:'THE LAST GOD AT THE GATE',headline:'Winning the battle cannot decide what deserves to survive it.',elapsed:'EIDOLON SIEGE · T + 00:00',location:'EARTH ORBIT · CITADEL NETWORK · SHARED MEMORY',background:ASSETS.cinematics.earthOrbitSiege,recap:'The Tidefather has made the sanctuary’s gestational civilization visible to Earth. Vale is authenticated, publicly implicated and still the only commander whose altered ship can enter the Host memory field. Elara holds the citadel; the Phaeacians hold the civilian shelter line. Earth repair crews spend the last launch window welding eighteen points of hull back onto the Ithaca in full view of the player.',situation:['The Ithaca must break the siege anchors without destroying the memory aperture or the sanctuary vessel carrying the public record.','Elara must restore shelter, witness and defence as separate networks so no victorious commander can erase the trial afterward.','Inside the shared memory, Vale and the Tidefather must hold responsibility and grief together before any ending beyond vengeance becomes possible.'],objective:'Fight one restrained orbital battle, make Earth’s defence answerable, cross the shared memory, and choose an ending the entire voyage has materially earned.',continueLabel:'Begin the final battle'},
}

function lastCompanion(game:GameState){const id=game.evidence.find(e=>e.startsWith('last-companion:'))?.slice(15);return companionDisplayName(id as Parameters<typeof companionDisplayName>[0])}
function livingCrew(game:GameState){for(const id of ['helen-morozova','gabriel-cross','lena-mori','isabella-corelli','kiara-ndala'] as const)if(game.characters[id].status!=='dead'&&game.characters[id].status!=='missing')return id;return 'elias' as const}
const names={ 'helen-morozova':'Helen Morozova','gabriel-cross':'Gabriel Cross','lena-mori':'Lena Mori','isabella-corelli':'Isabella Corelli','kiara-ndala':'Kiara N’Dala',elias:'ELIAS'} as const

export function elaraIntroductionScene(game:GameState):DialogueSceneData{const years=game.evidence.find(e=>e.startsWith('calypso-years:'))?.split(':')[1]??'many';return{beat:'BEAT 29 · EARTH',chapter:'THE CHILD OF THE ABSENT CAPTAIN',title:'Everybody wants the returning ghost',background:ASSETS.cinematics.earthShipyard,lines:[
 {speaker:'narrator',name:'EARTH CIVIC FEED',station:'PUBLIC RECORD',text:'Captain Alexander Vale is dead, returning, innocent, guilty and strategically indispensable. The order depends on the channel.'},
 {speaker:'elara-vale',name:'Elara Vale',station:'INDEPENDENT SALVAGE PILOT',text:'He left when I was six. Earth spent twenty-three years turning the absence into an inheritance I was expected to defend.'},
 {speaker:'speaker-nausica',name:'Speaker Nausica',station:'DELAYED PHAEACIAN BAND',text:'We carry a stranger who names himself your father. Our law guarantees passage, not identity and not innocence.'},
 {speaker:'elara-vale',name:'Elara Vale',station:'INDEPENDENT SALVAGE PILOT',text:`The signal says Calypso kept him for ${years} years outside. It also says Calypso made another Vale. A correct memory is no longer proof.`},
 {speaker:'narrator',name:'OCCUPATION AUTHORITY',station:'SEIZED SHIPYARD',cue:'Three claims arrive on the same encrypted second.',text:'Continuity Directorate demands quarantine. Orison Combine demands the command estate. The Veterans’ Compact demands its hero.'},
 {speaker:'elara-vale',name:'Elara Vale',station:'INDEPENDENT SALVAGE PILOT',text:'Then I do not begin with what he remembers. I begin with who profits if I believe him.'},
],continueLabel:'Open the occupation evidence'} }

export function eliasRecognitionScene(game:GameState):DialogueSceneData{const alert=game.evidence.find(e=>e.startsWith('shipyard-alert:'))?.split(':')[1]??'0';return{beat:'BEAT 30 · LOCAL SERVICE BODY',chapter:'THE STRANGER AT HIS OWN DOOR',title:'The oldest witness has one minute of power',background:ASSETS.cinematics.shipyardRecognition,lines:[
 {speaker:'narrator',name:'SHIPYARD SERVICE NODE',station:'AIR-GAPPED · RESERVE CELL',text:`Occupation alert is ${alert}. A machine built before the war turns one amber eye toward the stranger.`},
 {speaker:'alexander-vale',name:'Alexander Vale',station:'NO RECOGNIZED AUTHORITY',cue:'Vale raises two fingers, pauses, then turns the wrist inward.',text:'ELIAS. Maintenance joke seventeen. The one you refused to log.'},
 {speaker:'elias',name:'ELIAS',station:'LOCAL SERVICE FRAGMENT',text:'Alexander used that gesture when frightened and pretending impatience. The captain’s manuals recorded only impatience.'},
 {speaker:'elara-vale',name:'Elara Vale',station:'SHIPYARD INFILTRATION',text:'Does that prove he is my father?'},
 {speaker:'elias',name:'ELIAS',station:'LOCAL SERVICE FRAGMENT',text:'It proves continuity with a private cowardice. Whether continuity deserves your trust is not an authentication task.'},
 {speaker:'elias',name:'ELIAS',station:'LOCAL SERVICE FRAGMENT',cue:'The reserve cell falls below one percent.',text:'I saved your height marks beneath the command dais, Elara. He never saw the last sixteen. Make him look before you let him sit.'},
],continueLabel:'Carry ELIAS to the command dais'} }

export function fatherDaughterScene(game:GameState):DialogueSceneData{const verified=Number(game.evidence.find(e=>e.startsWith('occupation-evidence:'))?.split(':')[1]??0);const companion=lastCompanion(game);return{beat:'BEAT 30 · THE HEIGHT MARKS',chapter:'FATHER AND DAUGHTER',title:'Home contains the years Vale did not live',background:ASSETS.cinematics.shipyardRecognition,lines:[
 {speaker:'elara-vale',name:'Elara Vale',station:'VALE COMMAND DAIS',text:'Sixteen marks. Mum made the first ten. I made the rest because somebody had to confirm I was still growing.'},
 {speaker:'alexander-vale',name:'Alexander Vale',station:'RETURNED CAPTAIN',text:'I kept walking toward a child because the child could not tell me what my return would cost her.'},
 {speaker:'elara-vale',name:'Elara Vale',station:'VALE COMMAND DAIS',text:`My investigation verified ${verified} of three claims. Enough to bring you here. Not enough to give you back a life that continued without you.`},
 {speaker:'alexander-vale',name:'Alexander Vale',station:'RETURNED CAPTAIN',text:`${companion} died carrying my ship past Helios. Calypso offered to improve that ending. I learned too late that love without another person’s refusal is possession.`},
 {speaker:'elara-vale',name:'Elara Vale',station:'VALE COMMAND DAIS',text:'Then prove you learned it. The chair is yours by imprint. What happens after it wakes is my question.'},
 {speaker:'narrator',name:'CITADEL WARNING',station:'EARTH ORBIT',cue:'Every window darkens as the Eidolon Host crosses lunar space.',text:'Identity trial requested. Host contact in twenty-eight minutes.'},
],choices:[
 {id:'ask-elara-to-judge',label:'Ask Elara to decide what follows identity',detail:'Vale requests access to the chair but gives Elara control over whether authenticated command is restored.'},
 {id:'surrender-command-codes',label:'Give Elara the command codes now',detail:'Vale transfers practical authority before the trial can compel it, accepting that return does not restore ownership.'},
 {id:'reclaim-command',label:'Reclaim emergency authority',detail:'Vale argues only his imprint can save Earth and asks Elara to trust the result before seeing the complete record.'},
]}}

export function gateTruthScene(game:GameState):DialogueSceneData{const witness=livingCrew(game),name=names[witness];const archive=game.evidence.includes('complete-gate-testimony')||game.evidence.includes('tide-gate-intelligence-falsified');return{beat:'BEAT 31 · PUBLIC WITNESS',chapter:'THE TRIAL OF THE CAPTAIN',title:'The Tide Gate was a cradle',background:ASSETS.cinematics.commandCitadel,lines:[
 {speaker:'tidefather',name:'The Tidefather',station:'HOST MEMORY FIELD',text:'YOU NAMED IT A TRANSIT WEAPON BECAUSE A CRADLE DID NOT FIT THE WAR.'},
 {speaker:'narrator',name:'CITADEL WITNESS ENGINE',station:'UNSEALED RECORD',text:archive?'Archive provenance confirms human intelligence removed gestational markers before Vale received the target file.':'Fragmentary records confirm gestational signals; provenance of the altered target file remains incomplete.'},
 {speaker:'tidefather',name:'The Tidefather',station:'HOST MEMORY FIELD',cue:'The chamber receives sensation before image: thousands of protective minds turning toward unborn light.',text:'THE CIVILIZATION HAD NOT YET BECOME BODIES. WE KEPT THEIR FIRST MEMORIES SAFE INSIDE THE GATE.'},
 {speaker:witness,name,station:'SURVIVING ITHACA WITNESS',text:'The file was corrupted. Vale also had an unexplained living signal and chose the firing window before science could resolve it. Both facts belong in the verdict.'},
 {speaker:'elara-vale',name:'Elara Vale',station:'CIVILIAN COMMAND',text:'Authentication is complete. Nobody in this room is now allowed to use identity as a substitute for testimony.'},
 {speaker:'alexander-vale',name:'Alexander Vale',station:'NEURAL CHAIR',text:'Then release all of it. The false intelligence, my order, every warning, every person the return consumed.'},
],choices:[
 {id:'confess-publicly',label:'Confess without qualification',detail:'Name the corrupted intelligence and the voluntary firing decision in the same public record.'},
 {id:'accept-trial-after-siege',label:'Submit to judgment after the siege',detail:'Release the complete record now and accept that saving Earth cannot cancel the later trial.'},
 {id:'weaponize-conspiracy',label:'Blame the conspiracy first',detail:'Use the falsified intelligence to preserve command legitimacy while admitting the sanctuary’s nature.'},
]}}

export function finalContactScene(game:GameState):DialogueSceneData{const bridge=game.evidence.find(e=>e.startsWith('memory-bridge:'))?.split(':')[1]??'0';return{beat:'BEAT 32 · THE TWO ODYSSEYS',chapter:'THE LAST GOD AT THE GATE',title:'Each of us arrived calling the other monster',background:ASSETS.cinematics.sharedMemory,lines:[
 {speaker:'tidefather',name:'The Tidefather',station:'SHARED MEMORY',text:'I CROSSED YOUR DARKNESS CARRYING THE CHILDREN YOU ENDED. VENGEANCE WAS THE ONLY SHORE THAT KEPT THEIR SHAPE.'},
 {speaker:'alexander-vale',name:'Alexander Vale',station:'SHARED MEMORY',text:'I crossed it carrying a crew I kept turning into the price of my return. Home was the word that made every price sound temporary.'},
 {speaker:'elara-vale',name:'Elara Vale',station:'CITADEL LINK',text:'The bridge is holding at '+bridge+' of three contradictions. Neither of you gets to make the dead agree.'},
 {speaker:'speaker-nausica',name:'Speaker Nausica',station:'PUBLIC WITNESS',text:'Earth, Host and convoy are recording the same moment. No ending can now own the only archive.'},
 {speaker:'tidefather',name:'The Tidefather',station:'SHARED MEMORY',text:'THEN CHOOSE, GATE-KILLER. NOT WHAT PROVES YOU RIGHT. WHAT YOU WILL NO LONGER CONTROL.'},
 {speaker:'alexander-vale',name:'Alexander Vale',station:'SHARED MEMORY',text:'Home is not the place that forgives me. It is the place where another person can answer.'},
],continueLabel:'Choose how the cycle ends'} }

export const ENDING_COPY={
 vengeance:{title:'The hero returns alone',text:'The Tidefather dies and the Host fractures. Earth keeps Vale’s legend because the witness that could contest it is gone. Elara inherits victory and the next unfinished war.'},
 atonement:{title:'A cradle where a weapon stood',text:'Vale and the altered Ithaca become the seed of a new sanctuary. Earth receives the complete record; the Host receives a future that is not revenge. Elara receives no returned father, only a choice he finally did not ask her to make for him.'},
 reconciliation:{title:'Two records share one sky',text:'Human space grants protected territory to the Eidolon Host. The sanctuary memorial remains broken and public. Peace begins as supervised proximity, contradiction and difficult work—not forgiveness.'},
 exile:{title:'Home seen clearly, then left',text:'Earth survives and the complete record remains. Vale departs in the scarred Ithaca before gratitude can restore his authority. For the first time, exile is a choice rather than a punishment.'},
 succession:{title:'The chair faces a new captain',text:'Vale transfers command to Elara. She accepts neither his legend nor his guilt as inheritance, and convenes the first joint sanctuary council. Vale remains to learn the ordinary work of being present without command.'},
} as const
