import { useState } from 'react'
import type { EndingId, GameState } from '../state/types.js'
import { ASSETS } from './content.js'

export interface ActFourResult {
  choiceId: string
  success: boolean
  selections: string[]
  correct?: number
  mistakes?: number
  hullDamage?: number
  alert?: number
  bridge?: number
  ending?: EndingId
}

function Frame({ beat, title, goal, background, className = '', children }: { beat:string;title:string;goal:string;background:string;className?:string;children:React.ReactNode }) {
  return <section className={`act-four-game ${className}`} style={{'--act4-bg':`url(${background})`} as React.CSSProperties}><header><p>{beat}</p><h1>{title}</h1><strong>OBJECTIVE · {goal}</strong></header>{children}</section>
}

export const OCCUPATION_CASES = [
  {id:'arrival',name:'THE RETURN SIGNAL',question:'Which fact could not have been manufactured from public war records?',options:[
    {id:'heroic-codes',name:'Vale’s old command codes',detail:'Three occupying factions already possess partial copies.',correct:false},
    {id:'phaeacian-witness',name:'Independent Phaeacian memory bands',detail:'Five civilian recorders contain matching ship damage and testimony from before Earth received the signal.',correct:true},
    {id:'childhood-name',name:'Elara’s childhood call sign',detail:'The name appeared in a sealed but compromised family archive.',correct:false},
  ]},
  {id:'occupation',name:'THE SHIPYARD CLAIM',question:'Which record proves the occupation was planned before the return transmission?',options:[
    {id:'recent-patrols',name:'Current patrol routes',detail:'They prove control now, not when the seizure began.',correct:false},
    {id:'evacuation-hash',name:'Pre-dated evacuation order hash',detail:'The corporate order was signed eleven days before the first Phaeacian carrier wave.',correct:true},
    {id:'minister-speech',name:'A minister’s public warning',detail:'The speech followed the transmission and can be opportunism.',correct:false},
  ]},
  {id:'father',name:'THE PERSON RETURNING',question:'Which evidence distinguishes a living, accountable Vale from a useful heroic reconstruction?',options:[
    {id:'perfect-biometric',name:'Perfect archived biometrics',detail:'Calypso or the Host could reproduce a stored body pattern.',correct:false},
    {id:'unflattering-ledger',name:'The self-incriminating voyage ledger',detail:'It preserves decisions, contradictions and witnesses that weaken Vale’s claim to authority.',correct:true},
    {id:'victory-record',name:'The Tide Gate victory record',detail:'Every faction has edited this record to serve its claim.',correct:false},
  ]},
] as const

export function evidenceOutcome(selections:readonly string[]) { const correct=OCCUPATION_CASES.reduce((n,c,i)=>n+(c.options.find(o=>o.id===selections[i])?.correct?1:0),0);return{correct,mistakes:3-correct,success:correct>=2} }

export function OccupationEvidenceGame({onComplete}:{onComplete:(r:ActFourResult)=>void}){
  const [index,setIndex]=useState(0),[selections,setSelections]=useState<string[]>([]),[selected,setSelected]=useState<string|null>(null),[revealed,setRevealed]=useState(false)
  const item=OCCUPATION_CASES[index], chosen=item.options.find(o=>o.id===selected), running=evidenceOutcome([...selections,...(selected?[selected]:[])])
  const next=()=>{if(!selected)return;const all=[...selections,selected];if(index===2){const out=evidenceOutcome(all);onComplete({choiceId:`occupation:${all.join('+')}`,selections:all,...out});return}setSelections(all);setSelected(null);setRevealed(false);setIndex(v=>v+1)}
  return <Frame beat="BEAT 29 · INVESTIGATION" title="Decide who benefits from the ghost" goal="Test three claims with independently dated evidence before choosing whether the return signal deserves trust." background={ASSETS.cinematics.earthShipyard} className="occupation-game"><div className="act4-status"><span>CASE <b>{index+1}/3 · {item.name}</b></span><span>VERIFIED <b>{running.correct}</b></span><span>ELARA’S CONFIDENCE <b>{running.correct>=2?'CAUTIOUS':'UNSETTLED'}</b></span></div><div className="case-file"><strong>{item.question}</strong><span>Evidence must survive a hostile source, a copied identity and an interested faction.</span></div><div className="act4-options">{item.options.map(o=><button key={o.id} disabled={revealed} className={`${selected===o.id?'selected':''} ${revealed&&o.correct?'correct':''} ${revealed&&selected===o.id&&!o.correct?'wrong':''}`} onClick={()=>setSelected(o.id)}><strong>{o.name}</strong><small>{o.detail}</small>{revealed&&o.correct&&<span>INDEPENDENTLY VERIFIABLE</span>}</button>)}</div>{revealed?<div className={chosen?.correct?'act4-result success':'act4-result danger'}><strong>{chosen?.correct?'The claim survives contradiction.':'An adversary could manufacture this proof.'}</strong><span>Wrong conclusions do not restart the story; they make Elara’s later meeting more guarded.</span><button className="primary-action" onClick={next}>{index===2?'Commit Elara’s assessment':'Open next case'} <span>→</span></button></div>:<button className="primary-action" disabled={!selected} onClick={()=>setRevealed(true)}>Cross-examine this evidence <span>→</span></button>}</Frame>
}

const ESCAPE_LEGS=[
 {id:'dock',name:'LAUNCH WINDOW',correct:'freight-shadow',options:[{id:'patrol-gap',name:'Burn through patrol gap',detail:'Fast; every sensor sees the thermal plume.'},{id:'freight-shadow',name:'Match the ore barge',detail:'Slow; its authorized mass shadow conceals the shuttle.'},{id:'service-tube',name:'Enter service tube',detail:'The tube is physically sealed by occupation bulkheads.'}]},
 {id:'ring',name:'CORDON RING',correct:'cold-roll',options:[{id:'counterfire',name:'Arm defensive guns',detail:'Survival improves; Elara becomes the attack the occupation predicted.'},{id:'cold-roll',name:'Cut thrust and roll cold',detail:'Momentum crosses the scan plane without an engine signature.'},{id:'civilian-lane',name:'Hide in civilian traffic',detail:'Patrol fire would transfer risk to unarmed commuters.'}]},
 {id:'handoff',name:'PHAEACIAN HANDOFF',correct:'split-key',options:[{id:'broadcast-name',name:'Broadcast Elara’s name',detail:'Public identity is exactly what the factions are searching for.'},{id:'split-key',name:'Send two-part witness key',detail:'Neither the convoy nor shuttle holds enough data to betray the rendezvous alone.'},{id:'direct-beam',name:'Open a continuous beam',detail:'Clear and fast, but the cordon can trace it to both endpoints.'}]},
] as const
export function shuttleOutcome(s:readonly string[]){const mistakes=ESCAPE_LEGS.reduce((n,l,i)=>n+(s[i]===l.correct?0:1),0);return{mistakes,hullDamage:mistakes*5,success:mistakes<=1}}
export function ElaraShuttleEscapeGame({onComplete}:{onComplete:(r:ActFourResult)=>void}){const[index,setIndex]=useState(0),[s,setS]=useState<string[]>([]),[selected,setSelected]=useState<string|null>(null),[revealed,setRevealed]=useState(false);const leg=ESCAPE_LEGS[index],projected=shuttleOutcome([...s,...(selected?[selected]:[])]),correct=selected===leg.correct;const advance=()=>{if(!selected)return;const all=[...s,selected];if(index===2){const r=shuttleOutcome(all);onComplete({choiceId:`elara-escape:${all.join('+')}`,selections:all,...r});return}setS(all);setSelected(null);setRevealed(false);setIndex(v=>v+1)};return <Frame beat="BEAT 29 · SHUTTLE ESCAPE" title="Leave home without spending civilians" goal="Cross three surveillance layers. Read each threat; mistakes persist as shuttle damage instead of resetting the chase." background={ASSETS.cinematics.earthShipyard} className="shuttle-game"><div className="act4-status"><span>CORDON <b>{index+1}/3 · {leg.name}</b></span><span>ALERT <b>{projected.mistakes}/3</b></span><span>PROJECTED DAMAGE <b>−{projected.hullDamage}%</b></span></div><div className="shuttle-radar"><i/><i/><i/><strong>ELARA // SHUTTLE</strong><span>Read signature, momentum and who receives the danger before committing.</span></div><div className="act4-options">{leg.options.map(o=><button key={o.id} disabled={revealed} className={`${selected===o.id?'selected':''} ${revealed&&o.id===leg.correct?'correct':''} ${revealed&&selected===o.id&&o.id!==leg.correct?'wrong':''}`} onClick={()=>setSelected(o.id)}><strong>{o.name}</strong><small>{o.detail}</small></button>)}</div>{revealed?<div className={correct?'act4-result success':'act4-result danger'}><strong>{correct?'The shuttle crosses unseen.':'The cordon acquires a partial track.'}</strong><span>{correct?leg.options.find(o=>o.id===leg.correct)?.detail:'The chase continues; damage and alert remain in Elara’s record.'}</span><button className="primary-action" onClick={advance}>{index===2?'Reach the convoy':'Enter next cordon'} <span>→</span></button></div>:<button className="primary-action" disabled={!selected} onClick={()=>setRevealed(true)}>Commit maneuver <span>→</span></button>}</Frame>}

export const INFILTRATION_ZONES=[
 {name:'OCCUPATION CHECKPOINT',clue:'The forged evacuation order reserves freight maintenance—not officer access.',correct:'freight-lift',options:[{id:'command-door',name:'Use the command door'},{id:'freight-lift',name:'Ride the freight lift'},{id:'outer-hull',name:'Cross the exposed hull'}]},
 {name:'FAMILY ARCHIVE',clue:'The occupiers copied every code. They did not preserve the manual sequence Elara found in the pre-digital ledger.',correct:'manual-sequence',options:[{id:'voiceprint',name:'Submit Vale’s voiceprint'},{id:'manual-sequence',name:'Turn the dead mechanical tumblers'},{id:'override',name:'Burn an override charge'}]},
 {name:'SERVICE INTELLIGENCE',clue:'ELIAS was taught one gesture before the war; it never entered a networked training record.',correct:'old-gesture',options:[{id:'rank-code',name:'Issue a captain’s rank code'},{id:'old-gesture',name:'Make the two-finger maintenance gesture'},{id:'memory-upload',name:'Upload a childhood memory'}]},
] as const
export function infiltrationOutcome(s:readonly string[]){const alert=INFILTRATION_ZONES.reduce((n,z,i)=>n+(s[i]===z.correct?0:1),0);return{alert,success:alert<=1}}
export function ShipyardInfiltrationGame({onComplete}:{onComplete:(r:ActFourResult)=>void}){const[i,setI]=useState(0),[s,setS]=useState<string[]>([]),[selected,setSelected]=useState<string|null>(null),[revealed,setRevealed]=useState(false);const z=INFILTRATION_ZONES[i];const advance=()=>{if(!selected)return;const all=[...s,selected];if(i===2){const out=infiltrationOutcome(all);onComplete({choiceId:`shipyard:${all.join('+')}`,selections:all,...out});return}setS(all);setSelected(null);setRevealed(false);setI(v=>v+1)};return <Frame beat="BEAT 30 · INFILTRATION" title="Cross a home that remembers the wrong owner" goal="Use Elara’s evidence and Vale’s embodied memory to pass three occupied zones without turning recognition into a password." background={ASSETS.cinematics.shipyardRecognition} className="infiltration-game"><div className="act4-status"><span>ZONE <b>{i+1}/3 · {z.name}</b></span><span>ALERT <b>{infiltrationOutcome(s).alert}</b></span><span>ELIAS <b>{i===2?'NEAR':'DORMANT'}</b></span></div><div className="case-file"><strong>KNOWN BEFORE ENTRY</strong><span>{z.clue}</span></div><div className="act4-options">{z.options.map(o=><button key={o.id} disabled={revealed} className={`${selected===o.id?'selected':''} ${revealed&&o.id===z.correct?'correct':''}`} onClick={()=>setSelected(o.id)}><strong>{o.name}</strong></button>)}</div>{revealed?<div className={selected===z.correct?'act4-result success':'act4-result danger'}><strong>{selected===z.correct?'The route stays quiet.':'The occupation notices an inconsistency.'}</strong><span>{selected===z.correct?'This answer was established before the test.':'The scene continues with a higher citadel alert.'}</span><button className="primary-action" onClick={advance}>{i===2?'Let ELIAS answer':'Enter next zone'} <span>→</span></button></div>:<button className="primary-action" disabled={!selected} onClick={()=>setRevealed(true)}>Commit route <span>→</span></button>}</Frame>}

export const RESONANCE_ANCHORS=[
 {name:'BODY',prompt:'The chair receives two perfect neural patterns. What distinguishes continuity?',correct:'scar-history',options:[{id:'old-template',name:'Old biometric template'},{id:'scar-history',name:'Chronology of acquired scars'},{id:'command-key',name:'Command authority'}]},
 {name:'MEMORY',prompt:'Which memory cannot be safely reduced to a heroic identity claim?',correct:'contradiction',options:[{id:'gate-victory',name:'The Gate victory ceremony'},{id:'contradiction',name:'The preserved companion disagreement'},{id:'family-home',name:'The remembered family home'}]},
 {name:'OBLIGATION',prompt:'What does the chair require before restoring authority?',correct:'public-record',options:[{id:'obedience',name:'Proof the crew still obeys'},{id:'public-record',name:'Consent to release the complete voyage record'},{id:'bloodline',name:'Elara’s genetic confirmation'}]},
] as const
export function resonanceOutcome(s:readonly string[]){const correct=RESONANCE_ANCHORS.reduce((n,a,i)=>n+(s[i]===a.correct?1:0),0);return{correct,mistakes:3-correct,success:correct>=2}}
export function CommandResonanceGame({onComplete}:{onComplete:(r:ActFourResult)=>void}){const[i,setI]=useState(0),[s,setS]=useState<string[]>([]),[selected,setSelected]=useState<string|null>(null),[revealed,setRevealed]=useState(false);const a=RESONANCE_ANCHORS[i],correct=selected===a.correct,projected=resonanceOutcome([...s,...(selected?[selected]:[])]);const advance=()=>{if(!selected)return;const all=[...s,selected];if(i===2){const out=resonanceOutcome(all);onComplete({choiceId:`resonance:${all.join('+')}`,selections:all,...out});return}setS(all);setSelected(null);setRevealed(false);setI(v=>v+1)};return <Frame beat="BEAT 31 · COMMAND RESONANCE" title="Prove continuity without claiming innocence" goal="Wake the chair through body, memory and obligation. Authentication proves who Vale is; it cannot acquit what he did." background={ASSETS.cinematics.commandCitadel} className="resonance-game"><div className="act4-status"><span>ANCHOR <b>{i+1}/3 · {a.name}</b></span><span>RESONANCE <b>{projected.correct}/3</b></span><span>PUBLIC RECORD <b>{i===2?'ARMED':'SEALED'}</b></span></div><div className="resonance-rings"><i/><i/><i/><strong>{a.prompt}</strong></div><div className="act4-options">{a.options.map(o=><button key={o.id} disabled={revealed} className={`${selected===o.id?'selected':''} ${revealed&&o.id===a.correct?'correct':''} ${revealed&&selected===o.id&&o.id!==a.correct?'wrong':''}`} onClick={()=>setSelected(o.id)}><strong>{o.name}</strong></button>)}</div>{revealed?<div className={correct?'act4-result success':'act4-result danger'}><strong>{correct?'The chair accepts an outward anchor.':'The chair detects a reproducible claim.'}</strong><span>{correct?'Continuity is supported without converting it into innocence.':'Authentication continues, but this anchor could belong to a copy, office or legend.'}</span><button className="primary-action" onClick={advance}>{i===2?'Open the public witness':'Present next anchor'} <span>→</span></button></div>:<button className="primary-action" disabled={!selected} onClick={()=>setRevealed(true)}>Test resonance <span>→</span></button>}</Frame>}

const NETWORK_PHASES=[
 {name:'CIVILIAN SHELTERS',correct:'phaeacian-buffer',options:[{id:'weapon-grid',name:'Route through orbital guns',detail:'Fast, but drops fire control during the siege.'},{id:'phaeacian-buffer',name:'Use the Phaeacian sanctuary buffer',detail:'Keeps shelter power physically separate from weapons.'},{id:'medical-cell',name:'Drain emergency medicine',detail:'Stable power purchased with preventable deaths.'}]},
 {name:'PUBLIC WITNESS',correct:'split-ledger',options:[{id:'centralize',name:'Centralize under Vale'},{id:'split-ledger',name:'Mirror across Elara, Nausica and the Archive'},{id:'seal',name:'Seal until after victory'}]},
 {name:'DEFENCE CONTROL',correct:'elara-command',options:[{id:'vale-command',name:'Restore Vale’s exclusive authority'},{id:'elara-command',name:'Give Elara revocable civilian command'},{id:'autonomous-fire',name:'Release autonomous targeting'}]},
] as const
export function networkOutcome(s:readonly string[]){const correct=NETWORK_PHASES.reduce((n,p,i)=>n+(s[i]===p.correct?1:0),0);return{correct,mistakes:3-correct,success:correct>=2}}
export function CitadelNetworkGame({onComplete}:{onComplete:(r:ActFourResult)=>void}){const[i,setI]=useState(0),[s,setS]=useState<string[]>([]),[selected,setSelected]=useState<string|null>(null),[revealed,setRevealed]=useState(false);const p=NETWORK_PHASES[i],correct=selected===p.correct,projected=networkOutcome([...s,...(selected?[selected]:[])]);const advance=()=>{if(!selected)return;const all=[...s,selected];if(i===2){const out=networkOutcome(all);onComplete({choiceId:`citadel:${all.join('+')}`,selections:all,...out});return}setS(all);setSelected(null);setRevealed(false);setI(v=>v+1)};return <Frame beat="BEAT 32 · ELARA / CITADEL" title="Make Earth’s defence answerable" goal="Restore shelter, witness and weapons as separate systems so survival cannot erase accountability." background={ASSETS.cinematics.commandCitadel} className="network-game"><div className="act4-status"><span>NETWORK <b>{i+1}/3 · {p.name}</b></span><span>INTEGRITY <b>{projected.correct}/3</b></span><span>CONTROL <b>ELARA</b></span></div><div className="network-map"><i/><i/><i/><span>EARTH</span><span>CITADEL</span><span>CONVOY</span></div><div className="act4-options">{p.options.map(o=><button key={o.id} disabled={revealed} className={`${selected===o.id?'selected':''} ${revealed&&o.id===p.correct?'correct':''} ${revealed&&selected===o.id&&o.id!==p.correct?'wrong':''}`} onClick={()=>setSelected(o.id)}><strong>{o.name}</strong><small>{'detail'in o?o.detail:'Authority changes what survives after the battle.'}</small></button>)}</div>{revealed?<div className={correct?'act4-result success':'act4-result danger'}><strong>{correct?'Power and authority remain separable.':'The network works by concentrating an unreviewable cost.'}</strong><span>{correct?'This structure can survive the emergency without making it permanent.':'The finale continues, but the ending record preserves who lost control or protection.'}</span><button className="primary-action" onClick={advance}>{i===2?'Enter the shared memory':'Route next network'} <span>→</span></button></div>:<button className="primary-action" disabled={!selected} onClick={()=>setRevealed(true)}>Test this structure <span>→</span></button>}</Frame>}

const MEMORY_CLAIMS=[
 {name:'THE SANCTUARY',question:'What can remain true at the same time?',correct:'both-gate',options:[{id:'only-orders',name:'Vale obeyed corrupted orders, therefore the dead are not his responsibility.'},{id:'only-monster',name:'Vale chose the shot, therefore every later attempt at repair is manipulation.'},{id:'both-gate',name:'The intelligence was falsified and Vale still chose to fire before certainty.'}]},
 {name:'THE PURSUIT',question:'What does grief explain without permitting?',correct:'both-pursuit',options:[{id:'only-grief',name:'Grief makes every pursued human death necessary.'},{id:'only-war',name:'The Host attacked, so its original loss no longer matters.'},{id:'both-pursuit',name:'The Host’s grief is real; turning strangers into extensions of Vale repeats the crime.'}]},
 {name:'THE FUTURE',question:'What ends the cycle rather than winning it?',correct:'both-future',options:[{id:'erase-host',name:'Erase the opposing witness.'},{id:'restore-legend',name:'Restore the hero story Earth needs.'},{id:'both-future',name:'Preserve both records and place power where either can be contradicted.'}]},
] as const
export function memoryBridgeOutcome(s:readonly string[]){const bridge=MEMORY_CLAIMS.reduce((n,p,i)=>n+(s[i]===p.correct?1:0),0);return{bridge,success:bridge>=2}}
export function SharedMemoryGame({onComplete}:{onComplete:(r:ActFourResult)=>void}){const[i,setI]=useState(0),[s,setS]=useState<string[]>([]),[selected,setSelected]=useState<string|null>(null),[revealed,setRevealed]=useState(false);const p=MEMORY_CLAIMS[i],correct=selected===p.correct,projected=memoryBridgeOutcome([...s,...(selected?[selected]:[])]);const advance=()=>{if(!selected)return;const all=[...s,selected];if(i===2){const out=memoryBridgeOutcome(all);onComplete({choiceId:`shared-memory:${all.join('+')}`,selections:all,...out});return}setS(all);setSelected(null);setRevealed(false);setI(v=>v+1)};return <Frame beat="BEAT 32 · SHARED MEMORY" title="Hold two truths without making either disappear" goal="Cross three contested memories. A bridge requires responsibility and grief to remain visible together." background={ASSETS.cinematics.sharedMemory} className="memory-bridge-game"><div className="act4-status"><span>MEMORY <b>{i+1}/3 · {p.name}</b></span><span>BRIDGE <b>{projected.bridge}/3</b></span><span>TIDEFATHER <b>LISTENING</b></span></div><div className="case-file"><strong>{p.question}</strong><span>Answers that erase one witness strengthen vengeance even when they sound coherent.</span></div><div className="act4-options">{p.options.map(o=><button key={o.id} disabled={revealed} className={`${selected===o.id?'selected':''} ${revealed&&o.id===p.correct?'correct':''} ${revealed&&selected===o.id&&o.id!==p.correct?'wrong':''}`} onClick={()=>setSelected(o.id)}><strong>{o.name}</strong></button>)}</div>{revealed?<div className={correct?'act4-result success':'act4-result danger'}><strong>{correct?'Both witnesses remain present.':'One witness disappears from the answer.'}</strong><span>{correct?'The bridge gains one stable contradiction.':'The ending remains reachable, but reconciliation loses this anchor.'}</span><button className="primary-action" onClick={advance}>{i===2?'Hear the Tidefather answer':'Enter next memory'} <span>→</span></button></div>:<button className="primary-action" disabled={!selected} onClick={()=>setRevealed(true)}>Commit interpretation <span>→</span></button>}</Frame>}

export const ENDINGS:readonly {id:EndingId;name:string;promise:string;cost:string;requirement:string}[]=[
 {id:'vengeance',name:'Vengeance',promise:'Destroy the Tidefather and end the immediate siege.',cost:'Earth keeps the heroic legend; the opposing record dies with its witness.',requirement:'Always available after tactical victory.'},
 {id:'atonement',name:'Atonement',promise:'Use Vale and the Ithaca’s altered core to seed a new sanctuary.',cost:'Vale does not return. The crime is answered by a life, not erased by it.',requirement:'Expose the Tide Gate crime in public.'},
 {id:'reconciliation',name:'Reconciliation',promise:'Open protected human space to the Host and preserve both public records.',cost:'Earth must surrender innocence; the Host must surrender vengeance.',requirement:'Build the memory bridge, tell the Phaeacians the truth, and preserve the Helios remnant.'},
 {id:'exile',name:'Exile',promise:'Save Earth, publish the record, and leave before command becomes possession again.',cost:'Vale accepts that reaching home does not entitle him to remain.',requirement:'Always available after tactical victory.'},
 {id:'succession',name:'Succession',promise:'Transfer command to Elara and let the generation shaped by absence choose the peace.',cost:'Vale survives without controlling the meaning of his return.',requirement:'Build the memory bridge and earn Elara’s trust.'},
]
export function endingEligibility(game:GameState){const bridge=Number(game.evidence.find(e=>e.startsWith('memory-bridge:'))?.split(':')[1]??0);return{
 vengeance:true, atonement:game.flags.includes('tide-gate-crime-exposed'), exile:true,
 reconciliation:bridge>=2&&game.flags.includes('phaeacians-told-truth')&&game.flags.includes('helios-remnant-preserved'),
 succession:bridge>=2&&game.flags.includes('elara-trusts-vale')&&game.relationships['elara-vale']>=1,
 } satisfies Record<EndingId,boolean>}
export function EndingChoiceGame({game,onComplete}:{game:GameState;onComplete:(r:ActFourResult)=>void}){const eligible=endingEligibility(game),[selected,setSelected]=useState<EndingId|null>(null);const selectedData=ENDINGS.find(e=>e.id===selected);return <Frame beat="BEAT 32 · LAST CHOICE" title="Decide what home means after the truth" goal="Choose an earned ending. Locked resolutions show which relationship or act of accountability the voyage did not preserve." background={ASSETS.cinematics.sharedMemory} className="ending-choice-game"><div className="ending-grid">{ENDINGS.map(e=><button key={e.id} disabled={!eligible[e.id]} className={selected===e.id?'selected':''} onClick={()=>setSelected(e.id)}><span>{eligible[e.id]?'AVAILABLE':'NOT EARNED'}</span><strong>{e.name}</strong><small>{e.promise}</small><em>{eligible[e.id]?e.cost:e.requirement}</em></button>)}</div>{selectedData&&<div className="ending-confirm"><strong>{selectedData.name.toUpperCase()}</strong><span>{selectedData.cost}</span><button className="primary-action" onClick={()=>onComplete({choiceId:`ending:${selected}`,selections:[selected!],success:true,ending:selected!})}>End the cycle this way <span>→</span></button></div>}</Frame>}
