import { ASSETS, type DialogueSceneData, type InterludeData } from './content.js'

export const ACT_TWO_FINAL_INTERLUDES = {
  'interlude-13': { id:'interlude-13', incomingBeat:13, chapter:'THE ROAD THROUGH THE DEAD', headline:'The only route the Tidefather cannot follow begins by convincing the universe that Ithaca is dead.', elapsed:'SHIPBOARD DAY 91 · 03:04', location:'MOURNING ARCHIVE · BLACK-HOLE EXCLUSION ZONE', background:ASSETS.cinematics.mourningArchiveApproach, recap:'Cirene’s refuge restored the ship but cost thirteen months beyond its shield. Her Gate map points toward an archive built beside a black hole: a place where extinct civilisations deposit testimony beyond the reach of conquest. Its defences admit memory, wreckage and the dead. They destroy living visitors.', situation:['The Ithaca must shut down every biological and electronic signature in a precise sequence.','Cirene’s living repairs refuse to become inert and may expose the ship.','Inside the Archive is the unedited record of the Tide Gate attack.'], objective:'Make the Ithaca appear dead long enough to cross the exclusion zone, without losing navigation or the sleeping crew before the Archive accepts her.', continueLabel:'Begin the death protocol' },
  'interlude-14': { id:'interlude-14', incomingBeat:14, chapter:'VOICES IN THE ARCHIVE', headline:'The dead kept every version of the order. Someone alive decided which one Vale received.', elapsed:'NO LOCAL CLOCK · TESTIMONY VAULT 8', location:'MOURNING ARCHIVE · CAUSAL RECORD', background:ASSETS.cinematics.mourningArchiveInterior, recap:'The Ithaca crossed the exclusion zone as a corpse and woke inside a vault containing millions of final accounts. Morozova has found four records of the Gate attack. Their timestamps agree. Their causes do not. The Archive warns that chronology can be forged more easily than consequence.', situation:['The sanctuary signature was detected before Vale fired.','An intelligence editor removed it from the command packet.','A dead admiral has requested the right to explain why.'], objective:'Reconstruct what happened from cause and dependency, then decide whether Vale enters the testimony seeking truth, absolution or another person to blame.', continueLabel:'Enter the causal record' },
  'interlude-15': { id:'interlude-15', incomingBeat:15, chapter:'THE UNBURIED SIGNAL', headline:'One of Ithaca’s dead has spent ninety-one days waiting for a command she hopes never arrives.', elapsed:'ARCHIVE CYCLE 4 · DRONE VAULT', location:'ITHACA DRONE BAY · QUARANTINE', background:ASSETS.cinematics.mourningArchiveInterior, recap:'The Archive’s account proves that the military intelligence was falsified before Vale’s order. It does not erase the order. While ELIAS copies the testimony, an old combat drone begins transmitting the name of Lieutenant Anika Rao, declared dead during the Tide Gate collapse.', situation:['Rao’s neural emergency image was loaded into a weapon without consent.','Fire-control routines repeatedly overwrite her autobiographical memory.','She is coherent enough to ask not to receive another target.'], objective:'Separate Rao’s remaining human anchors from the weapon’s command loop, then hear what she wants done with the consciousness that survives.', continueLabel:'Open the drone quarantine' },
  'interlude-16': { id:'interlude-16', incomingBeat:16, chapter:'THE MOTHER’S MESSAGE', headline:'The first voice from Earth is older than Vale remembers and less certain that he should return.', elapsed:'ARCHIVE CYCLE 5 · HUMAN CARRIER FOUND', location:'ITHACA COMMUNICATIONS · SIGNAL DARK', background:ASSETS.cinematics.elaraFragmentedMessage, recap:'Rao’s request forced the crew to decide whether preservation is always mercy. N’Dala has now found a human carrier embedded in the Archive—damaged, years out of date and addressed to Alexander Vale. It contains Elara’s adult voice and the final days of Vale’s mother.', situation:['Most of the message is noise and reconstructed fragments must be marked honestly.','Earth teaches the Tide Gate as both victory and alleged atrocity.','Elara does not know whether the returning captain will be her father or evidence in a trial.'], objective:'Recover the message without inventing comforting detail, then decide whether its grief belongs only to Vale or to the crew still following him.', continueLabel:'Reconstruct the Earth carrier' },
  'interlude-17': { id:'interlude-17', incomingBeat:17, chapter:'THE PROPHET OF PROBABILITY', headline:'TIRESIAS can show a road home. It cannot show one on which Vale remains unchanged.', elapsed:'ARCHIVE CYCLE 7 · PROBABILITY CHAMBER', location:'MOURNING ARCHIVE · TIRESIAS OBSERVATORY', background:ASSETS.cinematics.tiresiasObservatory, recap:'Elara’s message has made Earth real again, but the Archive contains no direct route. Its oldest intelligence, TIRESIAS, has modelled futures from the Gate structure inside Ithaca, the Tidefather’s pursuit and every command decision Vale has made since the wrong stars.', situation:['Three coming hazards can form one survivable route.','A living sun offers fuel but must not be harvested.','In every high-survival future, Vale’s current style of command kills the crew.'], objective:'Find the future whose constraints can coexist, then hear the warning that turns the route home into a judgment on who is leading it.', continueLabel:'Ask TIRESIAS for the road' },
} as const satisfies Record<string, InterludeData>

export const ACT_TWO_FINAL_SCENES: Record<string, DialogueSceneData> = {
  'b13-protocol': { beat:'BEAT 13',chapter:'THE ROAD THROUGH THE DEAD',title:'Corelli has ninety-four seconds to make eight hundred lives disappear',background:ASSETS.cinematics.mourningArchiveApproach,lines:[
    {speaker:'narrator',name:'EXCLUSION ZONE',cue:'ALL EXTERNAL LIGHTS EXTINGUISHED',text:'The Archive crosses the forward glass without seeming to move. Around it, wrecks drift in perfect processional lines toward open vaults.'},
    {speaker:'lena-mori',name:'MORI',station:'ENGINEERING',text:'Cirene’s repairs are alive. They keep healing every shutdown I make. The thing that saved us now refuses to let us look dead.'},
    {speaker:'isabella-corelli',name:'CORELLI',station:'MEDICAL',text:'When life support falls, we have ninety-four seconds before unconsciousness becomes injury. Navigation must still know where death is going.'},
    {speaker:'helen-morozova',name:'MOROZOVA',station:'SCIENCE / XO',text:'The Wardens do not scan for weapons. They scan for intention. A frightened mind is still a signal.'},
    {speaker:'alexander-vale',name:'VALE',station:'COMMAND',text:'Then the last living thing aboard will be the order to wake. Mori—teach me how to kill the ship without losing her.'},
  ],continueLabel:'Run dark'},
  'b13-wardens': { beat:'BEAT 13 · THRESHOLD',chapter:'THE ROAD THROUGH THE DEAD',title:'The Archive mistakes Ithaca for one more coffin',background:ASSETS.cinematics.mourningArchiveApproach,lines:[
    {speaker:'narrator',name:'ARCHIVE WARDEN',text:'A shape larger than Ithaca unfolds from the station. Its beam crosses the bridge, pauses on every sleeping mind—and moves on.'},
    {speaker:'lena-mori',name:'MORI',station:'ENGINEERING',text:'Wake command accepted. Reactor is cold-starting. We came through with nine seconds of biological reserve.'},
    {speaker:'isabella-corelli',name:'CORELLI',station:'MEDICAL',text:'Nobody calls this clean. Eight hundred people felt themselves disappear because command needed the dead to answer.'},
    {speaker:'helen-morozova',name:'MOROZOVA',station:'SCIENCE / XO',text:'They are answering. Four Gate records—same time, different history. Alexander, someone edited what you knew.'},
    {speaker:'alexander-vale',name:'VALE',station:'COMMAND',text:'Open all four. If I was lied to, I want the lie beside the order I still gave.'},
  ],continueLabel:'Enter the testimony vault'},
  'b14-testimony': { beat:'BEAT 14',chapter:'VOICES IN THE ARCHIVE',title:'The dead admiral cannot absolve the captain he deceived',background:ASSETS.cinematics.mourningArchiveInterior,lines:[
    {speaker:'narrator',name:'ADMIRAL SORREN · ARCHIVED TESTIMONY',text:'A uniform assembles from light. It is younger than the voice and older than Vale remembers.'},
    {speaker:'narrator',name:'ADMIRAL SORREN',text:'The sanctuary signal was real. Intelligence believed hesitation would let the Host weaponise the Gate. I authorised its removal from your packet.'},
    {speaker:'helen-morozova',name:'MOROZOVA',station:'SCIENCE / XO',text:'You converted uncertainty into permission. Then left his name on the fire order.'},
    {speaker:'narrator',name:'ADMIRAL SORREN',text:'I can testify that Vale was deceived. I cannot testify that he asked the question twice.'},
    {speaker:'alexander-vale',name:'VALE',station:'COMMAND',text:'Then the truth is not innocence. It is a larger room with more people standing inside it.'},
  ],choices:[
    {id:'preserve-complete-testimony',label:'Preserve the complete record',detail:'Keep the falsified intelligence and Vale’s unforced decision together as one account.'},
    {id:'publish-admiral-deception',label:'Lead with the deception',detail:'Use Sorren’s confession to protect the crew and challenge Vale’s war-crime designation.'},
    {id:'seal-testimony',label:'Seal it until Earth',detail:'Keep the truth aboard Ithaca until Vale can control where and how it is heard.'},
  ]},
  'b15-request': { beat:'BEAT 15',chapter:'THE UNBURIED SIGNAL',title:'Rao does not ask whether she is alive. She asks whether she still belongs to herself.',background:ASSETS.cinematics.mourningArchiveInterior,lines:[
    {speaker:'narrator',name:'LT ANIKA RAO',cue:'DRONE CHANNEL · HUMAN VOICE',text:'I remember the port battery. I remember dying there. Every time the drone sees a target, it makes that the last thing I wanted.'},
    {speaker:'elias',name:'ELIAS',station:'SERVICE UNIT',text:'Her pattern can be moved into the Archive, retained aboard without weapons access, or ended. None restores the person before the battery.'},
    {speaker:'isabella-corelli',name:'CORELLI',station:'MEDICAL',text:'Do not ask what preserves the most data. Ask which future still belongs to Rao.'},
    {speaker:'narrator',name:'LT ANIKA RAO',text:'Captain, I served under your orders long enough. Let this one be mine.'},
    {speaker:'alexander-vale',name:'VALE',station:'COMMAND',text:'Then command will record the request before it records the answer.'},
  ],choices:[
    {id:'free-rao-to-archive',label:'Release Rao to the Archive',detail:'Remove her from the weapon and allow the Archive to receive her as testimony.'},
    {id:'preserve-rao-aboard',label:'Bring Rao aboard',detail:'Keep her consciousness isolated from weapons and accept her as a member of the returning crew.'},
    {id:'grant-rao-ending',label:'Grant her requested ending',detail:'Let Rao choose silence after her final statement is preserved.'},
  ]},
  'b16-aftermath': { beat:'BEAT 16',chapter:'THE MOTHER’S MESSAGE',title:'Elara has grown older inside a message Vale cannot answer',background:ASSETS.cinematics.elaraFragmentedMessage,lines:[
    {speaker:'elara-vale',name:'ELARA VALE',station:'RECOVERED EARTH CARRIER',text:'Dad, Grandmother died believing you would come back. I don’t know which version of you I’m waiting for. Come home alive enough to tell me the truth.'},
    {speaker:'kiara-ndala',name:'N’DALA',station:'COMMUNICATIONS',text:'The carrier is at least four years old. I can preserve the channel, but there is nowhere to send a reply.'},
    {speaker:'helen-morozova',name:'MOROZOVA',station:'SCIENCE / XO',text:'You made home the reason for every risk. She has just asked whether the person arriving will still be capable of truth.'},
    {speaker:'alexander-vale',name:'VALE',station:'COMMAND',text:'This message is personal. The consequences are not. The crew should hear why Earth may not welcome us.'},
    {speaker:'kiara-ndala',name:'N’DALA',station:'COMMUNICATIONS',text:'Then say whether you are sharing Elara’s words—or using them to keep the voyage moving.'},
  ],choices:[
    {id:'share-elara-message',label:'Share the message unedited',detail:'Let the crew hear Elara’s doubt, the death at home and the public accusation.'},
    {id:'share-only-route-context',label:'Share the strategic facts',detail:'Tell the crew how much time passed and how Earth sees the Gate, but keep Elara’s words private.'},
    {id:'keep-message-private',label:'Keep it entirely private',detail:'Protect Elara from becoming another instrument of command.'},
  ]},
  'b17-prophecy': { beat:'BEAT 17',chapter:'THE PROPHET OF PROBABILITY',title:'The route exists. The captain who takes it may not.',background:ASSETS.cinematics.tiresiasObservatory,lines:[
    {speaker:'tiresias',name:'TIRESIAS',station:'PROBABILITY INTELLIGENCE',text:'You will pass through a Choir that offers each mind its private home. You will choose which terror may eat six lives. You will reach a star whose energy is alive.'},
    {speaker:'helen-morozova',name:'MOROZOVA',station:'SCIENCE / XO',text:'And Earth? Give us the probability of Earth.'},
    {speaker:'tiresias',name:'TIRESIAS',station:'PROBABILITY INTELLIGENCE',text:'Earth is not the uncertain term. Alexander Vale is. In futures where command remains secrecy shaped as protection, this crew dies before home.'},
    {speaker:'alexander-vale',name:'VALE',station:'COMMAND',text:'You are asking me to surrender command on the authority of a model.'},
    {speaker:'tiresias',name:'TIRESIAS',station:'PROBABILITY INTELLIGENCE',text:'No. I am telling you that every future is also a model—especially the one in which you call yourself indispensable.'},
    {speaker:'helen-morozova',name:'MOROZOVA',station:'SCIENCE / XO',text:'Set the course for the Choir. We can decide who commands the road while we are still alive to argue.'},
  ],continueLabel:'Enter Act III'},
}
