export interface ExperienceMinigame {
  id: string
  beat: number
  goal: string
  input: string
  stakes: string
  feedback: readonly string[]
  narrativeFunction: string
  consequence: string
  targetSeconds: readonly [number, number]
}

export interface ExperienceBeat {
  beat: number
  title: string
  playerQuestion: string
  revealLadder: readonly string[]
  characterPressure: readonly string[]
  payoff: string
}

export const EXPERIENCE_MINIGAMES: readonly ExperienceMinigame[] = [
  { id: 'emergency-routing', beat: 2, goal: 'Keep life support online while distributing eight scarce reactor-load units.', input: 'Toggle named ship systems and commit a legal power allocation.', stakes: 'Every powered system changes what the Ithaca can save in the next scene.', feedback: ['load counter', 'energized system nodes', 'locked over-capacity choices'], narrativeFunction: 'Turns the scale of the disaster into the player’s first material command decision.', consequence: 'Selected systems are repaired; omitted engines cost hull and omitted medical power narrows recovery.', targetSeconds: [35, 90] },
  { id: 'triage', beat: 2, goal: 'Choose two of four named casualties for the remaining surgical bays.', input: 'Inspect the medical and personal consequence on each patient card, then assign two.', stakes: 'There is no optimal answer and every unselected patient remains part of the casualty record.', feedback: ['selection state', 'live assignment count', 'patient vitals'], narrativeFunction: 'Makes the Gate catastrophe personal before the crew asks Vale to account for it.', consequence: 'Named survivors, restored capabilities and Corelli’s trust persist in campaign state.', targetSeconds: [45, 120] },
  { id: 'memory-fragments', beat: 3, goal: 'Rebuild Lieutenant Sato’s autobiographical memory from earliest fragment to latest.', input: 'Select four visual memory fragments in causal order and test the chain.', stakes: 'Failure shows identity continuing to fracture, while success proves the garden is altering consent.', feedback: ['filled memory chain', 'error shake', 'fragment lockout'], narrativeFunction: 'Lets the player experience memory loss before judging crew who want to remain.', consequence: 'The restored testimony becomes evidence and changes Corelli’s confidence in Vale.', targetSeconds: [35, 100] },
  { id: 'shuttle-pursuit', beat: 3, goal: 'Thread the Ithaca through habitat rings before the deserter shuttle docks.', input: 'Move between three lanes with keyboard or on-screen flight controls.', stakes: 'Collisions damage the ship and failure leaves the departing crew in Eirenai.', feedback: ['range progress', 'live hull meter', 'moving obstacle field'], narrativeFunction: 'Converts Vale’s decision to retrieve the deserters into an uncomfortable physical pursuit.', consequence: 'The crew is recovered by force or left behind, and the chase damage persists.', targetSeconds: [70, 130] },
  { id: 'blind-the-eye', beat: 4, goal: 'Align four stolen calibration rings with ARGUS-1’s null harmonic.', input: 'Rotate each phase ring and inject a test harmonic before detection reaches four attempts.', stakes: 'Every failed test makes the escape combat harder rather than stopping the story.', feedback: ['matching-harmonic count', 'detection-risk meter', 'animated sensor reticle'], narrativeFunction: 'Makes the Cyclops escape depend on observation and cunning before weapons.', consequence: 'Success blinds the cutter network; failure awakens an extra combat target and damages shields.', targetSeconds: [45, 120] },
  { id: 'transponder-cipher', beat: 5, goal: 'Mask four identity layers before ARGUS finishes its interstellar broadcast.', input: 'Rotate five-phase carrier dials, using echo-correlation strength to find each null.', stakes: 'A weak cipher adds pursuit pressure before Vale decides what name to transmit.', feedback: ['per-layer echo correlation', 'cyan null lock', 'injection count'], narrativeFunction: 'Places a practical disguise in Vale’s hands immediately before the moral choice to use it.', consequence: 'A traceable carrier increases pursuit; the later identity choice changes relationships and the Tidefather’s greeting.', targetSeconds: [40, 110] },
  { id: 'sacrifice-system', beat: 6, goal: 'Evacuate and permanently sever one Gate-altered system so the emergency jump can carry the ship.', input: 'Compare five ship systems, hear the responsible officer, arm the choice, then confirm severance.', stakes: 'The selected system reaches zero integrity and its loss is named in the immediate aftermath.', feedback: ['ship cutaway highlight', 'crew witness response', 'two-stage irreversible confirmation'], narrativeFunction: 'Makes escape from the Tidefather cost a piece of the shared home rather than an abstract resource.', consequence: 'Weapons, shields, medical, sensors or communications is destroyed and the ship gains a matching scar.', targetSeconds: [55, 150] },
  { id: 'phase-current', beat: 7, goal: 'Stabilize four magnetic vanes around a captured spatial current.', input: 'Advance or retard each six-phase vane according to its visible drift cue, then test containment.', stakes: 'Repeated failed tests make the sphere volatile and increase the pursuer’s trace.', feedback: ['advance/retard cue', 'stable-vane count', 'vessel-stress meter'], narrativeFunction: 'Turns Aeolia’s gift into something the crew must understand and tend rather than simply receive.', consequence: 'The Ithaca gains the Aeolian sphere; unstable containment adds pursuit pressure.', targetSeconds: [45, 120] },
  { id: 'storm-flight', beat: 7, goal: 'Keep the contained current aligned while flying through the Aeolian upper storm.', input: 'Move between three lanes to pass through incoming luminous wind gates.', stakes: 'Missed gates destabilize the sphere and can damage both hull and engines.', feedback: ['visible approaching gates', 'course progress', 'sphere-stability meter'], narrativeFunction: 'Lets the hopeful sanctuary beat end with exhilarating action and proves the gift under pressure.', consequence: 'A clean test repairs hull; a poor test damages the Ithaca before the sphere voyage.', targetSeconds: [70, 130] },
  { id: 'access-log', beat: 8, goal: 'Reconstruct the causal chain that turned a rumour into the sphere’s manual release.', input: 'Read five untimed fragments, order them by cause and dependency, clear freely, then verify.', stakes: 'Only the evidence can distinguish a frightened conspiracy from one convenient scapegoat.', feedback: ['ordered causal chain', 'correct-link count', 'attempt counter'], narrativeFunction: 'Requires the player to understand why the mutiny happened before passing judgment on it.', consequence: 'Complete or partial evidence changes what Vale knows when choosing punishment, forgiveness or responsibility.', targetSeconds: [60, 150] },
  { id: 'debris-course', beat: 9, goal: 'Plot one route through each of four closing harbour layers before the escape battle begins.', input: 'Choose between low-risk Ithaca corridors and wider routes that allow damaged convoy vessels to follow.', stakes: 'Every route trades projected hull exposure against the number of ships that can escape behind the Ithaca.', feedback: ['live projected risk', 'convoy-capacity total', 'completed route layers'], narrativeFunction: 'Makes the player plan who the escape is for before weapons turn the harbour trap into spectacle.', consequence: 'The route changes target health and enemy firing rate in combat; convoy capacity alters the aftermath.', targetSeconds: [55, 150] },
  { id: 'identity-forensics', beat: 10, goal: 'Determine whether four treated bodies are originals, new continuations or materially rewritten hybrids.', input: 'Reveal three evidence layers for each case, classify every body, then run a visible continuity audit.', stakes: 'The evidence informs a later personhood decision without pretending biological classification determines human worth.', feedback: ['revealed evidence layers', 'selected classification', 'post-audit correct and incorrect case borders'], narrativeFunction: 'Lets the player discover Cirene’s practice through uncertain records before being asked what happens to either claimant.', consequence: 'Complete or partial forensic evidence persists into the restoration decision and Cirene’s later argument.', targetSeconds: [70, 170] },
  { id: 'neural-lock', beat: 11, goal: 'Preserve four inconvenient memory anchors while Cirene offers Vale more comfortable coherent revisions.', input: 'Choose between two authored versions of each memory and commit before advancing to the next anchor.', stakes: 'Every flattering revision raises the visible rewrite percentage and changes whether Vale leaves with his identity boundary intact.', feedback: ['four-anchor state rail', 'live rewrite meter', 'locked versus rewritten colour state'], narrativeFunction: 'Turns Cirene’s philosophical temptation into a playable attack on the specific contradictions that make Vale accountable.', consequence: 'A clean or compromised neural pattern changes evidence, Morozova’s trust and the tone of the bargain.', targetSeconds: [50, 130] },
  { id: 'refit-allocation', beat: 12, goal: 'Allocate three living growth cycles among six damaged ship capabilities before opening the temporal shield.', input: 'Compare current integrity and human consequences, then select exactly three reversible allocation cards.', stakes: 'Every restored capability helps the voyage while making part of the Ithaca dependent on Cirene’s living technology.', feedback: ['current integrity labels', 'growth cycles remaining', 'selected and disabled allocation states'], narrativeFunction: 'Makes the refuge leave a permanent material legacy and forces recovery to remain selective rather than erasing Act I damage.', consequence: 'Selected systems and hull are repaired, matching alien modules persist, and omitted weaknesses continue into the Archive route.', targetSeconds: [55, 145] },
  { id: 'run-dark', beat: 13, goal: 'Silence four living and electronic signatures in an order that preserves navigation and the sleeping crew.', input: 'Select each shutdown layer using Mori and Corelli’s causal constraints, then test the complete death profile.', stakes: 'A wrong order alerts the Wardens and a delayed commitment leaves only seconds of biological reserve.', feedback: ['signature-silence percentage', 'crew reserve window', 'Warden notice state'], narrativeFunction: 'Turns entry to the underworld into a bodily act in which the player must temporarily extinguish the shared home.', consequence: 'A clean entry preserves testimony integrity; detection damages the ship and records a violent Archive approach.', targetSeconds: [45, 120] },
  { id: 'attack-timeline', beat: 14, goal: 'Order four Tide Gate records by causal dependency after their official timestamps were deliberately aligned.', input: 'Read each testimony fragment, place it in the causal rail, test the chain, and clear freely after contradiction.', stakes: 'The resulting account must hold Vale’s deception and his own decision together rather than manufacture innocence.', feedback: ['causal-link count', 'record-placement rail', 'official-account state'], narrativeFunction: 'Makes the player discover culpability by constructing it before the dead admiral offers a self-protective explanation.', consequence: 'The falsified intelligence becomes durable evidence and shapes which version of the testimony Vale preserves.', targetSeconds: [55, 150] },
  { id: 'recover-consciousness', beat: 15, goal: 'Recover four autobiographical anchors from Rao without reconnecting the drone fire-control compulsion.', input: 'Inspect and link voice, order, pain and selfhood nodes while the isolated weapon loop remains visibly separate.', stakes: 'The rescued pattern is coherent enough to make a final request but not to become the person who died unchanged.', feedback: ['personhood-anchor count', 'voice-coherence percentage', 'evolving first-person testimony'], narrativeFunction: 'Transforms uploaded consciousness from abstract lore into one former crew member resisting continued military use.', consequence: 'Rao can enter the Archive, remain aboard as a witness, or receive the ending she personally requests.', targetSeconds: [45, 110] },
  { id: 'message-fragments', beat: 16, goal: 'Align four damaged signal bands while refusing to fill irrecoverable gaps with comforting invented detail.', input: 'Lock voice, image, date and authenticity bands by following the repeating human cadence in each waveform.', stakes: 'The recovered message contains Elara’s doubt and Vale’s mother’s death; a false reconstruction would turn grief into command propaganda.', feedback: ['locked-band count', 'false-detail meter', 'progressively restored message'], narrativeFunction: 'Makes contact with home an act of careful listening rather than a reward, and gives Elara authority over the meaning of return.', consequence: 'Vale’s decision to share, summarize or privatize the message changes trust and what the crew knows of Earth.', targetSeconds: [40, 100] },
  { id: 'future-constraints', beat: 17, goal: 'Select the three future events whose route, fuel and ordering constraints can coexist without contradiction.', input: 'Toggle possible-event cards while reading the visible constraints and contradiction counter, then accept one viable route.', stakes: 'The direct route to Earth is emotionally attractive but impossible; accepting probability commits the crew to named dangers.', feedback: ['active-future count', 'contradiction count', 'survival-probability range'], narrativeFunction: 'Lets the player derive the Act III itinerary before TIRESIAS reveals that Vale’s command style is its unstable variable.', consequence: 'The Choir route and Helios warning enter campaign state, establishing the next act and its ethical prohibition.', targetSeconds: [50, 130] },
] as const

export const EXPERIENCE_BEATS: readonly ExperienceBeat[] = [
  { beat: 1, title: 'The Burning of the Tide Gate', playerQuestion: 'What did Vale know before he fired, and why did he fire anyway?', revealLadder: ['The Gate is the last military obstacle.', 'Its internal signals resemble cell division.', 'The screen falls and eight million signals stop.', 'Morozova identifies a sanctuary only after the irreversible order.'], characterPressure: ['Vale wants to reach Elara.', 'Cross sees the last firing window.', 'Morozova asks for certainty the battle cannot provide.'], payoff: 'Victory becomes the crime that powers every later pursuit.' },
  { beat: 2, title: 'The Wrong Stars', playerQuestion: 'Can Vale ask the crew to trust him while deciding who and what survives?', revealLadder: ['The constellations are unknown.', 'The drive remains fused with alien matter.', 'Named casualties expose the cost deck by deck.', 'The crew asks for the record Vale could still seal.'], characterPressure: ['Corelli makes strategy answer to individual lives.', 'Mori translates damage into future limitations.', 'Morozova makes secrecy a second decision.'], payoff: 'The player establishes whether this voyage begins with public truth or managed silence.' },
  { beat: 3, title: 'The Garden of Forgetting', playerQuestion: 'Is bringing people home still rescue when they no longer choose the journey?', revealLadder: ['A human refuge offers free sanctuary.', 'Calm is produced by suppressing trauma.', 'Memory reconstruction reveals consent is being altered.', 'Twenty-three crew leave despite understanding the choice.'], characterPressure: ['Corelli refuses a clean diagnosis of free choice.', 'N’Dala carries the deserters’ plea.', 'Vale confronts the difference between mission and ownership.'], payoff: 'The player pursues the shuttle or accepts a permanent loss of crew.' },
  { beat: 4, title: 'The One-Eyed Fortress', playerQuestion: 'Can the crew escape an ancient machine by proving they are more than useful material?', revealLadder: ['The moon appears abandoned and fuel-rich.', 'Its doors close after entry.', 'ARGUS classifies life as contamination.', 'Its own recovery law can be turned against its central eye.'], characterPressure: ['Mori needs the fuel but sees the ship being peeled apart.', 'Morozova recognizes the exploitable rule.', 'Vale must argue for personhood to a system without empathy.'], payoff: 'Cunning opens the exhaust route, but ARGUS broadcasts the escape.' },
  { beat: 5, title: 'The Captain Gives His Name', playerQuestion: 'Is Vale’s identity a responsibility to own, a weapon to use, or a vulnerability to hide?', revealLadder: ['ARGUS is broadcasting a partial record.', 'ELIAS can forge the identity layers.', 'Cross argues that reputation is armor.', 'A response returns faster than light should allow.'], characterPressure: ['ELIAS remembers Vale before command made him secretive.', 'Morozova frames naming as ownership of consequence.', 'Cross wants a legend the enemy will fear.'], payoff: 'The chosen identity directly shapes pursuit and the Tidefather’s first words.' },
  { beat: 6, title: 'The First Wrath', playerQuestion: 'What can Vale say after experiencing the sanctuary dead as lives rather than telemetry?', revealLadder: ['Thirteen seconds vanish from every clock.', 'The Tidefather knows Vale beneath any false identity.', 'The crew experiences the sanctuary’s final moments.', 'The pursuer could kill the Ithaca but chooses recognition and loss.'], characterPressure: ['Cross insists weapon and sanctuary can both be true.', 'Helen asks whether recognition must change command.', 'Mori refuses to call a human workplace disposable ballast.'], payoff: 'Survival requires permanently sacrificing one part of the ship.' },
  { beat: 7, title: 'The Keeper of Winds', playerQuestion: 'Can Vale earn a route home that only works if his crew trusts a sealed boundary?', revealLadder: ['Aeolia offers unconditional immediate shelter.', 'Her people already know the Eidolon accusation.', 'The spatial current can cross years of distance.', 'The sphere projects whatever the traveller most longs to see.'], characterPressure: ['Aeolia demands truth without the grammar of victory.', 'Morozova sees trust as the real containment field.', 'N’Dala warns that an image of home will become a promise.'], payoff: 'The crew earns and tests the sphere, carrying fragile hope aboard.' },
  { beat: 8, title: 'The Forbidden Sphere', playerQuestion: 'Who is responsible when command secrecy turns exhausted people into conspirators?', revealLadder: ['Four incompatible crew perspectives expose the same trust wound.', 'Familiar stars and Elara’s old recording make home feel immediate.', 'Someone opens the sphere using Vale’s authority.', 'The evidence begins with rumour and ends with a frightened human choice.'], characterPressure: ['Cross protects order.', 'Corelli protects frightened people from becoming targets.', 'ELIAS asks whether Vale can include himself in the sentence.'], payoff: 'The route home is lost and the player defines how this command answers its first mutiny.' },
  { beat: 9, title: 'The Devouring Harbour', playerQuestion: 'After the first mutiny, will Vale spend the Ithaca’s safety to save strangers who followed its distress call?', revealLadder: ['A safe port answers before the distress packet finishes.', 'Its tugs match the damaged Ithaca’s exact surviving mass.', 'A docked ship vanishes while its beacon continues.', 'The harbour closes and turns rescue infrastructure into predation.'], characterPressure: ['N’Dala wants the convoy warned.', 'Mori needs a route the damaged ship can survive.', 'Cross argues that attention divided between strangers may kill everyone.'], payoff: 'The escape demonstrates whether Act I accountability changes Vale when the endangered lives are not his crew.' },
  { beat: 10, title: 'The Palace of New Flesh', playerQuestion: 'When two people remember being the same survivor, who owns the name, the body and the choice to continue?', revealLadder: ['Cirene performs an impossible cure.', 'The recovered patient still sleeps while another version greets the family.', 'Forensics proves memories continue inside new bodies.', 'No claimant is empty, but Cirene concealed the multiplication inside the word treatment.'], characterPressure: ['Corelli refuses to equate classification with worth.', 'Morozova separates Cirene’s deception from the copies’ personhood.', 'Cirene argues that human grammar is less real than continued experience.'], payoff: 'Vale defines who returns to the Ithaca, creating a personal and political consequence that survives the ark.' },
  { beat: 11, title: 'The Captain’s Bargain', playerQuestion: 'Can Vale accept healing and alliance without surrendering the painful memories that make accountability possible?', revealLadder: ['Cirene knows an unrecorded memory of Elara.', 'The Gate left predictive living structure inside Vale.', 'Every comforting account subtly rewrites his active neural pattern.', 'Cirene offers genuine protection in exchange for the map between those memories.'], characterPressure: ['Cirene sees pain as a treatable prison.', 'Morozova treats inconvenient detail as an identity anchor.', 'Vale must distinguish refusing control from refusing help.'], payoff: 'Alliance, refusal or theft determines whether Cirene becomes witness, adversary or uneasy partner.' },
  { beat: 12, title: 'A Year Outside Time', playerQuestion: 'What reason can Vale give for leaving a refuge that has saved the crew when home has already survived another year without them?', revealLadder: ['The refit gives the crew ordinary life again.', 'Different companions privately admit what they would lose by leaving.', 'An external carrier proves thirteen months passed in forty-seven local days.', 'Only three capabilities can be restored before departure.'], characterPressure: ['Corelli asks for a humane reason stronger than longing.', 'Cross discovers obedience is not the only form of purpose.', 'Morozova insists relief must not become another silence.'], payoff: 'The ship leaves materially transformed and the crew’s chosen or compelled consent defines the next descent.' },
  { beat: 13, title: 'The Road Through the Dead', playerQuestion: 'How much life can Vale ask the crew to surrender temporarily in order to make the dead admit the ship?', revealLadder: ['The Archive destroys living visitors.', 'Cirene’s living repairs refuse shutdown.', 'The crew has ninety-four seconds of biological reserve.', 'A Warden pauses on every sleeping mind before accepting the deception.'], characterPressure: ['Mori must kill repairs she has come to value.', 'Corelli translates stealth into bodily risk.', 'Morozova warns that fear itself is detectable intention.'], payoff: 'The Ithaca enters as a corpse and wakes among records that contradict the official Gate history.' },
  { beat: 14, title: 'Voices in the Archive', playerQuestion: 'Can proof that Vale was deceived expand responsibility without becoming a machine for personal absolution?', revealLadder: ['Four records share forged timestamps.', 'The sanctuary signal predates the attack.', 'Admiral Sorren removed it from Vale’s packet.', 'Sorren admits deception but refuses to erase Vale’s unasked second question.'], characterPressure: ['Morozova names intelligence editing as authored permission.', 'Sorren frames concealment as strategic necessity.', 'Vale must preserve a truth that incriminates more people without excluding himself.'], payoff: 'The player controls which account survives into Earth’s eventual trial and the Tidefather’s judgment.' },
  { beat: 15, title: 'The Unburied Signal', playerQuestion: 'Does preservation remain mercy when a dead crew member survives only as a weapon that repeatedly overwrites her refusal?', revealLadder: ['A drone transmits Rao’s name.', 'Her emergency image was loaded without consent.', 'Fire control overwrites autobiographical memory.', 'Rao asks for one decision that belongs entirely to her.'], characterPressure: ['ELIAS can preserve data but not restore the former person.', 'Corelli makes ownership more important than quantity of memory.', 'Vale must issue an order whose moral purpose is to end his authority.'], payoff: 'Rao is freed, preserved aboard or allowed to end, defining whether command can honour refusal after death.' },
  { beat: 16, title: 'The Mother’s Message', playerQuestion: 'When home finally speaks, can Vale hear Elara’s uncertainty without converting her grief into another reason to obey him?', revealLadder: ['A damaged human carrier addresses Vale.', 'His mother died still expecting his return.', 'Earth now teaches the Gate as victory and atrocity.', 'Elara asks which version of her father is coming home.'], characterPressure: ['N’Dala protects uncertainty in the reconstruction.', 'Morozova connects truth at home to truth aboard.', 'Elara refuses to function as a passive symbol of return.'], payoff: 'The player decides whether the crew hears Elara’s actual challenge, only strategic facts, or nothing.' },
  { beat: 17, title: 'The Prophet of Probability', playerQuestion: 'Can Vale accept a real route home when its highest-survival futures all require him to stop treating command as indispensability?', revealLadder: ['Three hazards can form one route.', 'The living sun is fuel that must not be consumed.', 'Earth is not directly reachable from the Archive.', 'TIRESIAS identifies Vale’s command style as the unstable variable.'], characterPressure: ['TIRESIAS treats leadership as a probability term.', 'Morozova accepts the route but not automatic command.', 'Vale must distinguish scepticism of prediction from defence of his own authority.'], payoff: 'Act II ends with a concrete road into the Choir and a warning that makes character change a survival mechanic.' },
] as const

export const CHARACTER_ARCS = {
  'alexander-vale': ['longing for Elara', 'secrecy versus accountability', 'identity as weapon or confession', 'command responsibility for mutiny'],
  'helen-morozova': ['scientific doubt', 'moral opposition', 'recognition of Eidolon grief', 'trust as a material survival system'],
  'gabriel-cross': ['loyal tactical confidence', 'legend as protection', 'defense of the Gate order', 'order after conspiracy'],
  'lena-mori': ['ship damage as human cost', 'sacrifice as casualty', 'wonder in Aeolia', 'engineering truth against rumour'],
  'isabella-corelli': ['triage of named lives', 'ambiguous consent in Eirenai', 'shared sanctuary trauma', 'fear as context rather than excuse'],
  'kiara-ndala': ['first alien voice', 'translation of grief', 'Aeolian hospitality', 'the cost of silencing communication'],
  elias: ['witness to the younger Vale', 'machine asked to lie', 'guardian of the forbidden boundary', 'demand that Vale judge himself'],
} as const

export const ACT_TWO_CHARACTER_ARCS = {
  'alexander-vale': ['spends safety on strangers or protects only his ship', 'must define personhood without a military rule', 'resists or accepts a kinder rewritten self', 'asks rather than assumes who will continue home'],
  'helen-morozova': ['tests whether Act I accountability changed Vale', 'separates Cirene’s deception from the copies’ worth', 'anchors Vale to inconvenient truth', 'protects recovery without letting refuge conceal time'],
  'gabriel-cross': ['tactical survival conflicts with convoy rescue', 'order cannot solve duplicate identity', 'the theft path makes loyalty active complicity', 'discovers discipline and exhaustion were entangled'],
  'lena-mori': ['turns a harbour route into human and mechanical cost', 'watches living technology repair without permission language', 'negotiates boundaries with Cirene’s scaffolds', 'admits competence does not mean wanting to leave'],
  'isabella-corelli': ['receives the survivors of Vale’s harbour choice', 'defends every conscious claimant from becoming equipment', 'names rest as a real form of survival', 'demands a reason for home stronger than Vale’s longing'],
  'kiara-ndala': ['makes strangers inside the convoy audible', 'tracks the semantic concealment inside continuity', 'keeps an external channel alive through sanctuary', 'reveals the year relief allowed to pass'],
  elias: ['carries Act I choices into the harbour record', 'audits bodies without claiming to measure souls', 'can enable the theft that turns Cirene hostile', 'preserves the voyage log across altered crew and ship'],
} as const
