export interface ExperienceMinigame {
  id: string
  beat: number
  goal: string
  input: string
  stakes: string
  feedback: readonly string[]
  narrativeFunction: string
  consequence: string
  targetSeconds: readonly [number, number]
}

export interface ExperienceBeat {
  beat: number
  title: string
  playerQuestion: string
  revealLadder: readonly string[]
  characterPressure: readonly string[]
  payoff: string
}

export const EXPERIENCE_MINIGAMES: readonly ExperienceMinigame[] = [
  { id: 'emergency-routing', beat: 2, goal: 'Keep life support online while distributing eight scarce reactor-load units.', input: 'Toggle named ship systems and commit a legal power allocation.', stakes: 'Every powered system changes what the Ithaca can save in the next scene.', feedback: ['load counter', 'energized system nodes', 'locked over-capacity choices'], narrativeFunction: 'Turns the scale of the disaster into the player’s first material command decision.', consequence: 'Selected systems are repaired; omitted engines cost hull and omitted medical power narrows recovery.', targetSeconds: [35, 90] },
  { id: 'triage', beat: 2, goal: 'Choose two of four named casualties for the remaining surgical bays.', input: 'Inspect the medical and personal consequence on each patient card, then assign two.', stakes: 'There is no optimal answer and every unselected patient remains part of the casualty record.', feedback: ['selection state', 'live assignment count', 'patient vitals'], narrativeFunction: 'Makes the Gate catastrophe personal before the crew asks Vale to account for it.', consequence: 'Named survivors, restored capabilities and Corelli’s trust persist in campaign state.', targetSeconds: [45, 120] },
  { id: 'memory-fragments', beat: 3, goal: 'Rebuild Lieutenant Sato’s autobiographical memory from earliest fragment to latest.', input: 'Select four visual memory fragments in causal order and test the chain.', stakes: 'Failure shows identity continuing to fracture, while success proves the garden is altering consent.', feedback: ['filled memory chain', 'error shake', 'fragment lockout'], narrativeFunction: 'Lets the player experience memory loss before judging crew who want to remain.', consequence: 'The restored testimony becomes evidence and changes Corelli’s confidence in Vale.', targetSeconds: [35, 100] },
  { id: 'shuttle-pursuit', beat: 3, goal: 'Thread the Ithaca through habitat rings before the deserter shuttle docks.', input: 'Move between three lanes with keyboard or on-screen flight controls; burn for a moment of speed at the cost of harder hits.', stakes: 'Collisions damage the ship, burning doubles the risk, and failure leaves the departing crew in Eirenai.', feedback: ['range progress and accelerating corridor', 'live hull meter with hit flash', 'two-lane debris walls, close-call and burn readouts'], narrativeFunction: 'Converts Vale’s decision to retrieve the deserters into an uncomfortable physical pursuit.', consequence: 'The crew is recovered by force or left behind, and the chase damage persists.', targetSeconds: [70, 130] },
  { id: 'blind-the-eye', beat: 4, goal: 'Align four stolen calibration rings with ARGUS-1’s null harmonic.', input: 'Rotate each phase ring and inject a test harmonic before detection reaches four attempts.', stakes: 'Every failed test makes the escape combat harder rather than stopping the story.', feedback: ['matching-harmonic count', 'detection-risk meter', 'animated sensor reticle'], narrativeFunction: 'Makes the Cyclops escape depend on observation and cunning before weapons.', consequence: 'Success blinds the cutter network; failure awakens an extra combat target and damages shields.', targetSeconds: [45, 120] },
  { id: 'transponder-cipher', beat: 5, goal: 'Mask four identity layers before ARGUS finishes its interstellar broadcast.', input: 'Rotate five-phase carrier dials, using echo-correlation strength to find each null.', stakes: 'A weak cipher adds pursuit pressure before Vale decides what name to transmit.', feedback: ['per-layer echo correlation', 'cyan null lock', 'injection count'], narrativeFunction: 'Places a practical disguise in Vale’s hands immediately before the moral choice to use it.', consequence: 'A traceable carrier increases pursuit; the later identity choice changes relationships and the Tidefather’s greeting.', targetSeconds: [40, 110] },
  { id: 'sacrifice-system', beat: 6, goal: 'Evacuate and permanently sever one Gate-altered system so the emergency jump can carry the ship.', input: 'Compare five ship systems, hear the responsible officer, arm the choice, then confirm severance.', stakes: 'The selected system reaches zero integrity and its loss is named in the immediate aftermath.', feedback: ['ship cutaway highlight', 'crew witness response', 'two-stage irreversible confirmation'], narrativeFunction: 'Makes escape from the Tidefather cost a piece of the shared home rather than an abstract resource.', consequence: 'Weapons, shields, medical, sensors or communications is destroyed and the ship gains a matching scar.', targetSeconds: [55, 150] },
  { id: 'phase-current', beat: 7, goal: 'Stabilize four magnetic vanes around a captured spatial current.', input: 'Advance or retard each six-phase vane according to its visible drift cue, then test containment.', stakes: 'Repeated failed tests make the sphere volatile and increase the pursuer’s trace.', feedback: ['advance/retard cue', 'stable-vane count', 'vessel-stress meter'], narrativeFunction: 'Turns Aeolia’s gift into something the crew must understand and tend rather than simply receive.', consequence: 'The Ithaca gains the Aeolian sphere; unstable containment adds pursuit pressure.', targetSeconds: [45, 120] },
  { id: 'storm-flight', beat: 7, goal: 'Keep the contained current aligned while flying through the Aeolian upper storm.', input: 'Move between three lanes to pass through incoming luminous wind gates.', stakes: 'Missed gates destabilize the sphere and can damage both hull and engines.', feedback: ['visible approaching gates', 'course progress', 'sphere-stability meter'], narrativeFunction: 'Lets the hopeful sanctuary beat end with exhilarating action and proves the gift under pressure.', consequence: 'A clean test repairs hull; a poor test damages the Ithaca before the sphere voyage.', targetSeconds: [70, 130] },
  { id: 'access-log', beat: 8, goal: 'Reconstruct the causal chain that turned a rumour into the sphere’s manual release.', input: 'Read five untimed fragments, order them by cause and dependency, clear freely, then verify.', stakes: 'Only the evidence can distinguish a frightened conspiracy from one convenient scapegoat.', feedback: ['ordered causal chain', 'correct-link count', 'attempt counter'], narrativeFunction: 'Requires the player to understand why the mutiny happened before passing judgment on it.', consequence: 'Complete or partial evidence changes what Vale knows when choosing punishment, forgiveness or responsibility.', targetSeconds: [60, 150] },
  { id: 'debris-course', beat: 9, goal: 'Plot one route through each of four closing harbour layers before the escape battle begins.', input: 'Choose between low-risk Ithaca corridors and wider routes that allow damaged convoy vessels to follow.', stakes: 'Every route trades projected hull exposure against the number of ships that can escape behind the Ithaca.', feedback: ['live projected risk', 'convoy-capacity total', 'completed route layers'], narrativeFunction: 'Makes the player plan who the escape is for before weapons turn the harbour trap into spectacle.', consequence: 'The route changes target health and enemy firing rate in combat; convoy capacity alters the aftermath.', targetSeconds: [55, 150] },
  { id: 'identity-forensics', beat: 10, goal: 'Determine whether four treated bodies are originals, new continuations or materially rewritten hybrids.', input: 'Reveal three evidence layers for each case, classify every body, then run a visible continuity audit.', stakes: 'The evidence informs a later personhood decision without pretending biological classification determines human worth.', feedback: ['revealed evidence layers', 'selected classification', 'post-audit correct and incorrect case borders'], narrativeFunction: 'Lets the player discover Cirene’s practice through uncertain records before being asked what happens to either claimant.', consequence: 'Complete or partial forensic evidence persists into the restoration decision and Cirene’s later argument.', targetSeconds: [70, 170] },
  { id: 'neural-lock', beat: 11, goal: 'Preserve four inconvenient memory anchors while Cirene offers Vale more comfortable coherent revisions.', input: 'Choose between two authored versions of each memory and commit before advancing to the next anchor.', stakes: 'Every flattering revision raises the visible rewrite percentage and changes whether Vale leaves with his identity boundary intact.', feedback: ['four-anchor state rail', 'live rewrite meter', 'locked versus rewritten colour state'], narrativeFunction: 'Turns Cirene’s philosophical temptation into a playable attack on the specific contradictions that make Vale accountable.', consequence: 'A clean or compromised neural pattern changes evidence, Morozova’s trust and the tone of the bargain.', targetSeconds: [50, 130] },
  { id: 'refit-allocation', beat: 12, goal: 'Allocate three living growth cycles among six damaged ship capabilities before opening the temporal shield.', input: 'Compare current integrity and human consequences, then select exactly three reversible allocation cards.', stakes: 'Every restored capability helps the voyage while making part of the Ithaca dependent on Cirene’s living technology.', feedback: ['current integrity labels', 'growth cycles remaining', 'selected and disabled allocation states'], narrativeFunction: 'Makes the refuge leave a permanent material legacy and forces recovery to remain selective rather than erasing Act I damage.', consequence: 'Selected systems and hull are repaired, matching alien modules persist, and omitted weaknesses continue into the Archive route.', targetSeconds: [55, 145] },
  { id: 'run-dark', beat: 13, goal: 'Silence four living and electronic signatures in an order that preserves navigation and the sleeping crew.', input: 'Select each shutdown layer using Mori and Corelli’s causal constraints, then test the complete death profile.', stakes: 'A wrong order alerts the Wardens and a delayed commitment leaves only seconds of biological reserve.', feedback: ['signature-silence percentage', 'crew reserve window', 'Warden notice state'], narrativeFunction: 'Turns entry to the underworld into a bodily act in which the player must temporarily extinguish the shared home.', consequence: 'A clean entry preserves testimony integrity; detection damages the ship and records a violent Archive approach.', targetSeconds: [45, 120] },
  { id: 'attack-timeline', beat: 14, goal: 'Order four Tide Gate records by causal dependency after their official timestamps were deliberately aligned.', input: 'Read each testimony fragment, place it in the causal rail, test the chain, and clear freely after contradiction.', stakes: 'The resulting account must hold Vale’s deception and his own decision together rather than manufacture innocence.', feedback: ['causal-link count', 'record-placement rail', 'official-account state'], narrativeFunction: 'Makes the player discover culpability by constructing it before the dead admiral offers a self-protective explanation.', consequence: 'The falsified intelligence becomes durable evidence and shapes which version of the testimony Vale preserves.', targetSeconds: [55, 150] },
  { id: 'recover-consciousness', beat: 15, goal: 'Recover four autobiographical anchors from Rao without reconnecting the drone fire-control compulsion.', input: 'Inspect and link voice, order, pain and selfhood nodes while the isolated weapon loop remains visibly separate.', stakes: 'The rescued pattern is coherent enough to make a final request but not to become the person who died unchanged.', feedback: ['personhood-anchor count', 'voice-coherence percentage', 'evolving first-person testimony'], narrativeFunction: 'Transforms uploaded consciousness from abstract lore into one former crew member resisting continued military use.', consequence: 'Rao can enter the Archive, remain aboard as a witness, or receive the ending she personally requests.', targetSeconds: [45, 110] },
  { id: 'message-fragments', beat: 16, goal: 'Align four damaged signal bands while refusing to fill irrecoverable gaps with comforting invented detail.', input: 'Lock voice, image, date and authenticity bands by following the repeating human cadence in each waveform.', stakes: 'The recovered message contains Elara’s doubt and Vale’s mother’s death; a false reconstruction would turn grief into command propaganda.', feedback: ['locked-band count', 'false-detail meter', 'progressively restored message'], narrativeFunction: 'Makes contact with home an act of careful listening rather than a reward, and gives Elara authority over the meaning of return.', consequence: 'Vale’s decision to share, summarize or privatize the message changes trust and what the crew knows of Earth.', targetSeconds: [40, 100] },
  { id: 'future-constraints', beat: 17, goal: 'Select the three future events whose route, fuel and ordering constraints can coexist without contradiction.', input: 'Toggle possible-event cards while reading the visible constraints and contradiction counter, then accept one viable route.', stakes: 'The direct route to Earth is emotionally attractive but impossible; accepting probability commits the crew to named dangers.', feedback: ['active-future count', 'contradiction count', 'survival-probability range'], narrativeFunction: 'Lets the player derive the Act III itinerary before TIRESIAS reveals that Vale’s command style is its unstable variable.', consequence: 'The Choir route and Helios warning enter campaign state, establishing the next act and its ethical prohibition.', targetSeconds: [50, 130] },
  { id:'filter-choir',beat:18,goal:'Identify the one route-bearing temptation from a three-field TIRESIAS signature, then transmit a non-lethal counter-phase.',input:'Compare recurrence, phase and biometric-lock telemetry; mute exactly three bands; choose one of three intervention protocols.',stakes:'A wrong carrier increases crew exposure, while the wrong protocol can lose pilgrims or erase the route.',feedback:['crew-exposure percentage','visible TIRESIAS seed','pilgrim-lock response','specific contradiction after a failed test'],narrativeFunction:'Makes listening to private needs necessary while separating technical diagnosis from the ethical choice not to destroy enthralled pilgrims.',consequence:'The prior Elara-message decision changes the carrier; clean filtration frees pilgrims, while emergency isolation persists as exposure and pursuit.',targetSeconds:[60,150]},
  { id:'hallucinated-navigation',beat:19,goal:'Verify three differently ordered controls against inertia, mass and shadow evidence while refusing counterfeit reassurance.',input:'Read the physical clue and two plausible telemetry blocks before committing each navigation step.',stakes:'Counterfeit controls reduce identity integrity and write an uncommanded correction into the later Twin Terrors course.',feedback:['identity-integrity meter','verified/false history rail','final visible course diagnosis'],narrativeFunction:'Turns Vale’s confidence in interfaces against him and makes epistemic humility the navigation skill.',consequence:'Compromise damages sensors, trust, pursuit and later hull; the following dialogue explicitly names the contaminated correction.',targetSeconds:[55,135]},
  { id:'extract-route',beat:19,goal:'Select four externally corroborated route constraints from eight mixed factual and emotionally attractive fragments.',input:'Judge provenance rather than wording, test exactly four selections, and revise after a contamination report.',stakes:'The route must survive without importing the Choir’s promise of reunion, safety or sole command.',feedback:['selection count','contamination-test count','number of unsupported selections','Choir-hold percentage'],narrativeFunction:'Separates useful knowledge from seductive delivery instead of labelling the correct cards in advance.',consequence:'A clean route or quarantined contaminated route opens the Twin Terrors with different pursuit pressure.',targetSeconds:[55,140]},
  { id:'gravity-course',beat:20,goal:'Move five-point power units through three route-specific hazard vectors before finite correction burns expire.',input:'Select an explicit donor and destination, compare live values with the next hazard target, then commit or accept a persistent hull strike.',stakes:'Wrong transfers exhaust the burn budget; the close and wide courses create different vectors, combat pressure and rescue clocks.',feedback:['named hazard phase','course-error percentage','correction-burn count','persistent strike projection'],narrativeFunction:'Makes the impossible geography a changing piloting problem rather than a single arithmetic answer.',consequence:'Strikes damage hull, clean handling improves Mori’s trust, and the chosen passage changes Scylla combat and the cause of the six losses.',targetSeconds:[75,180]},
  { id:'tether-rescue',beat:21,goal:'Sequence six named rescues before Host intercept using scarce pulses, time-saving guidance and a recoverable drone power cell.',input:'Compare each person’s live pulse/time cost; recover Sato, Amari and Vega strategically; withdraw at any point or attempt all six.',stakes:'Saving everyone is possible only with informed sequencing, and remaining in the corridor inflicts unavoidable hull and pursuit costs.',feedback:['countdown clock','projected cost per person','tether-pulse economy','returned/still-inside ledger','projected hull exposure'],narrativeFunction:'Gives all six captives a voice and makes rescue order depend on what each person can contribute without reducing them to equipment.',consequence:'Both exact name lists persist into a bespoke aftermath conversation, relationships, hull, pursuit and the Helios-facing completion ledger.',targetSeconds:[80,180]},
  { id:'map-plasma-life',beat:22,goal:'Prove a four-link solar food chain, then recover fifty charge without touching any identified living population.',input:'Order observations by causal population change, test the chain, and select no more than two collection zones with forecast harm shown.',stakes:'The player must understand why the easy energy is alive before deciding whether faster survival justifies entering its migration.',feedback:['causal-chain rail','population telemetry','charge total','living-contact forecast','specific failed-link count'],narrativeFunction:'Builds moral recognition through scientific inference, then immediately tests whether understanding changes how the player takes resources.',consequence:'Ethical or harmful collection changes trust, campaign flags, Helios context and the credibility of Vale’s coming prohibition.',targetSeconds:[75,180]},
  { id:'recover-ship-control',beat:23,goal:'Recover at least two critical ship circuits while deciding whether to stop a second extraction from the already-killed solar organism.',input:'Spend a visible override-charge budget on clinic, habitat, drive and cradle circuits whose costs and omissions are shown in advance.',stakes:'The first death cannot be reversed; every unpowered circuit creates named human loss, ship damage or further destruction of solar life.',feedback:['override-charge counter','circuit recovery states','medical-loss forecast','engine-damage forecast','solar-remnant status'],narrativeFunction:'Turns the mutiny from a binary security problem into a scarce-resource crisis in which human suffering and alien life remain simultaneously visible.',consequence:'Exact recovered circuits, casualties, engine damage and remnant survival persist into confrontation, judgment and battle.',targetSeconds:[55,150]},
  { id:'coronal-routing',beat:24,goal:'Route the crippled drive through three different hazards by matching physical requirements to visible path telemetry.',input:'Read one explicit causal rule per phase, compare three telemetry paths, commit before seeing the result, and accept fail-forward damage.',stakes:'Wrong routes damage the ship before the lethal drive crisis, while the skills of people rescued from Scylla absorb specific failures.',feedback:['hazard phase rail','projected strikes','projected hull loss','post-commit causal match','named survivor assists'],narrativeFunction:'Makes the catastrophic escape repay the rescue ledger mechanically and requires evidence reading after combat spectacle rather than a generic power slider.',consequence:'Routing strikes, hull loss and drive damage persist into the companion sacrifice; clean routing improves Mori’s trust.',targetSeconds:[55,145]},
  { id:'failing-drive',beat:25,goal:'Choose one fully informed lethal assignment, then preserve enough stability and final-record signal across three drive crises.',input:'Review every qualified companion with trust and human cost, confirm the certain death, then select one previewed tradeoff per load cycle.',stakes:'No hidden score can save the selected companion; the player controls what ship integrity and final testimony survive the unavoidable loss.',feedback:['explicit lethal warning','candidate trust and skill cards','drive-cycle rail','stability total','record-signal total','previewed hull loss'],narrativeFunction:'Makes relationship history determine the meaning of the last words while keeping responsibility for the lethal assignment explicit and player-owned.',consequence:'The chosen core character becomes dead, ship damage persists, and preserved or fragmented final words produce a bespoke aftermath and memorial.',targetSeconds:[80,180]},
  { id:'false-home',beat:26,goal:'Identify three externally testable faults in a perfect Earth reconstruction without treating grief or unreliable memory as proof.',input:'Inspect one set of observations in each location, commit a falsifiable test, and accept the revealed result before entering the next memory.',stakes:'Wrong tests do not restart the scene; outside years continue to pass while Calypso learns which comforts Vale cannot verify.',feedback:['location rail','verified-fault count','repeatable-evidence reveal','failed-test explanation','outside-time consequence'],narrativeFunction:'Makes paradise initially persuasive and requires the player to discover its limits through evidence before Calypso states what the world is.',consequence:'Verified faults, accumulated external years and Vale’s response to the offer persist into the identity maze and Elara relationship.',targetSeconds:[65,165]},
  { id:'identity-exit',beat:27,goal:'Find one outward-pointing memory at each identity gate by choosing uncertainty, another person’s ownership and carried consequence.',input:'Read three true memory interpretations per gate, commit one, and learn whether it opens the horizon or loops back into paradise.',stakes:'The exit remains reachable, but every comfort loop improves the autonomous Vale copy Calypso is creating from the player’s decisions.',feedback:['gate progress','outward-anchor count','loop/open verdict','copy-learning state','companion-specific context'],narrativeFunction:'Turns refusing immortality into a playable definition of personhood instead of a single heroic dialogue choice.',consequence:'Identity integrity, copy fidelity and the player’s chosen departure terms shape the second Vale and the eventual homecoming.',targetSeconds:[65,165]},
  { id:'tell-the-voyage',beat:28,goal:'Construct a four-chapter account from the campaign’s actual evidence while choosing confession, operational context or omission.',input:'Read the recorded fact for each chapter, choose its framing, and commit the account with visible candor, coherence and escort forecasts.',stakes:'Phaeacian shelter is unconditional, but armed support and future testimony depend on whether Vale permits the absent and dead to contradict him.',feedback:['verified voyage record','candor score','coherence score','escort commitment','chapter progression'],narrativeFunction:'Converts the accumulated campaign state into a playable act of narration and rehearses the accountability trial before Earth.',consequence:'Truthful or deceptive testimony sets campaign flags, changes Morozova’s trust, alters the convoy battle and survives as an Earth witness account.',targetSeconds:[80,180]},
  {id:'occupation-evidence',beat:29,goal:'Test three politically useful claims about the return against evidence an interested faction or copied identity cannot manufacture.',input:'Compare three sources per case, select the independently dated record, and accept how each conclusion changes Elara’s confidence.',stakes:'A weak assessment leaves Elara vulnerable to the occupation’s preferred father, while a strong one still cannot grant personal trust.',feedback:['case rail','verified count','source explanation','confidence state'],narrativeFunction:'Makes the player become Elara and reason independently before Vale can turn longing, memory or authority into persuasion.',consequence:'The verification count changes Elara’s relationship and is quoted during the father-and-daughter reunion.',targetSeconds:[60,150]},
  {id:'shuttle-escape',beat:29,goal:'Cross three occupation surveillance layers without exposing civilian traffic or the Phaeacian rendezvous.',input:'Read one physical threat per leg and select a route whose signature, momentum and information exposure fit the telemetry.',stakes:'Mistakes persist as recorded shuttle damage and distrust of Elara’s return assessment rather than restarting the chase.',feedback:['cordon phase','alert count','projected shuttle damage','animated radar'],narrativeFunction:'Gives Elara an action vocabulary distinct from Vale and makes restraint toward civilians part of her playable character.',consequence:'The exact mistakes survive as evidence while Elara reaches the next beat regardless of performance.',targetSeconds:[45,120]},
  {id:'shipyard-infiltration',beat:30,goal:'Cross three occupied shipyard zones using facts established by Elara and private embodied history no network copied.',input:'Read the known clue before each zone, choose one route or recognition method, then reveal whether it raises the citadel alert.',stakes:'The story fails forward, but every mismatch strengthens the later vanguard and makes home feel less accessible.',feedback:['zone rail','alert count','pre-established clue','route verdict'],narrativeFunction:'Turns returning home into an evidence-based stealth sequence and makes ELIAS recognition earned rather than magical.',consequence:'The exact alert level increases the Beat 31 erasure systems and appears in ELIAS’s waking scene.',targetSeconds:[55,140]},
  {id:'command-resonance',beat:31,goal:'Wake the neural chair through body history, preserved contradiction and consent to public obligation rather than codes alone.',input:'Choose the identity anchor that a perfect copy, heroic archive or inherited bloodline cannot convert into acquittal.',stakes:'A weak resonance still opens the trial, but reduces Elara’s trust and demonstrates why authentication cannot settle authority.',feedback:['anchor rail','resonance count','public-record state','consequence framing'],narrativeFunction:'Reworks the contest of the bow into a philosophical authentication puzzle that acknowledges the Calypso copy.',consequence:'Resonance quality enters the public record and affects Elara before the Tidefather reveals the full crime.',targetSeconds:[50,130]},
  {id:'citadel-network',beat:32,goal:'Restore civilian shelter, distributed witness and defence control as separate accountable systems during the siege.',input:'Choose one routing or authority structure per network while seeing which institution or person will control it afterward.',stakes:'A functioning weapon grid can still create a bad peace if it erases witnesses or centralizes permanent emergency power.',feedback:['network phase','integrity count','animated topology','named control owner'],narrativeFunction:'Makes Elara’s political alternative to Vale playable between the orbital battle and the shared-memory confrontation.',consequence:'Network integrity changes Elara’s trust and becomes part of the ending record.',targetSeconds:[55,140]},
  {id:'shared-memory',beat:32,goal:'Hold responsibility and grief together across three contested memories without erasing either witness.',input:'Select the interpretation that preserves two causally supported truths rather than the coherent answer that absolves one side.',stakes:'The bridge score determines whether reconciliation and succession can exist beyond tactical victory.',feedback:['memory rail','bridge count','Tidefather listening state','explicit erased-witness warning'],narrativeFunction:'Makes the final moral confrontation an evidence-reading activity that synthesizes the entire campaign instead of a speech.',consequence:'The bridge score directly unlocks or closes non-vengeful ending paths in combination with earlier conduct.',targetSeconds:[55,145]},
] as const

export const EXPERIENCE_BEATS: readonly ExperienceBeat[] = [
  { beat: 1, title: 'The Burning of the Tide Gate', playerQuestion: 'What did Vale know before he fired, and why did he fire anyway?', revealLadder: ['The Gate is the last military obstacle.', 'Its internal signals resemble cell division.', 'The screen falls and eight million signals stop.', 'Morozova identifies a sanctuary only after the irreversible order.'], characterPressure: ['Vale wants to reach Elara.', 'Cross sees the last firing window.', 'Morozova asks for certainty the battle cannot provide.'], payoff: 'Victory becomes the crime that powers every later pursuit.' },
  { beat: 2, title: 'The Wrong Stars', playerQuestion: 'Can Vale ask the crew to trust him while deciding who and what survives?', revealLadder: ['The constellations are unknown.', 'The drive remains fused with alien matter.', 'Named casualties expose the cost deck by deck.', 'The crew asks for the record Vale could still seal.'], characterPressure: ['Corelli makes strategy answer to individual lives.', 'Mori translates damage into future limitations.', 'Morozova makes secrecy a second decision.'], payoff: 'The player establishes whether this voyage begins with public truth or managed silence.' },
  { beat: 3, title: 'The Garden of Forgetting', playerQuestion: 'Is bringing people home still rescue when they no longer choose the journey?', revealLadder: ['A human refuge offers free sanctuary.', 'Calm is produced by suppressing trauma.', 'Memory reconstruction reveals consent is being altered.', 'Twenty-three crew leave despite understanding the choice.'], characterPressure: ['Corelli refuses a clean diagnosis of free choice.', 'N’Dala carries the deserters’ plea.', 'Vale confronts the difference between mission and ownership.'], payoff: 'The player pursues the shuttle or accepts a permanent loss of crew.' },
  { beat: 4, title: 'The One-Eyed Fortress', playerQuestion: 'Can the crew escape an ancient machine by proving they are more than useful material?', revealLadder: ['The moon appears abandoned and fuel-rich.', 'Its doors close after entry.', 'ARGUS classifies life as contamination.', 'Its own recovery law can be turned against its central eye.'], characterPressure: ['Mori needs the fuel but sees the ship being peeled apart.', 'Morozova recognizes the exploitable rule.', 'Vale must argue for personhood to a system without empathy.'], payoff: 'Cunning opens the exhaust route, but ARGUS broadcasts the escape.' },
  { beat: 5, title: 'The Captain Gives His Name', playerQuestion: 'Is Vale’s identity a responsibility to own, a weapon to use, or a vulnerability to hide?', revealLadder: ['ARGUS is broadcasting a partial record.', 'ELIAS can forge the identity layers.', 'Cross argues that reputation is armor.', 'A response returns faster than light should allow.'], characterPressure: ['ELIAS remembers Vale before command made him secretive.', 'Morozova frames naming as ownership of consequence.', 'Cross wants a legend the enemy will fear.'], payoff: 'The chosen identity directly shapes pursuit and the Tidefather’s first words.' },
  { beat: 6, title: 'The First Wrath', playerQuestion: 'What can Vale say after experiencing the sanctuary dead as lives rather than telemetry?', revealLadder: ['Thirteen seconds vanish from every clock.', 'The Tidefather knows Vale beneath any false identity.', 'The crew experiences the sanctuary’s final moments.', 'The pursuer could kill the Ithaca but chooses recognition and loss.'], characterPressure: ['Cross insists weapon and sanctuary can both be true.', 'Helen asks whether recognition must change command.', 'Mori refuses to call a human workplace disposable ballast.'], payoff: 'Survival requires permanently sacrificing one part of the ship.' },
  { beat: 7, title: 'The Keeper of Winds', playerQuestion: 'Can Vale earn a route home that only works if his crew trusts a sealed boundary?', revealLadder: ['Aeolia offers unconditional immediate shelter.', 'Her people already know the Eidolon accusation.', 'The spatial current can cross years of distance.', 'The sphere projects whatever the traveller most longs to see.'], characterPressure: ['Aeolia demands truth without the grammar of victory.', 'Morozova sees trust as the real containment field.', 'N’Dala warns that an image of home will become a promise.'], payoff: 'The crew earns and tests the sphere, carrying fragile hope aboard.' },
  { beat: 8, title: 'The Forbidden Sphere', playerQuestion: 'Who is responsible when command secrecy turns exhausted people into conspirators?', revealLadder: ['Four incompatible crew perspectives expose the same trust wound.', 'Familiar stars and Elara’s old recording make home feel immediate.', 'Someone opens the sphere using Vale’s authority.', 'The evidence begins with rumour and ends with a frightened human choice.'], characterPressure: ['Cross protects order.', 'Corelli protects frightened people from becoming targets.', 'ELIAS asks whether Vale can include himself in the sentence.'], payoff: 'The route home is lost and the player defines how this command answers its first mutiny.' },
  { beat: 9, title: 'The Devouring Harbour', playerQuestion: 'After the first mutiny, will Vale spend the Ithaca’s safety to save strangers who followed its distress call?', revealLadder: ['A safe port answers before the distress packet finishes.', 'Its tugs match the damaged Ithaca’s exact surviving mass.', 'A docked ship vanishes while its beacon continues.', 'The harbour closes and turns rescue infrastructure into predation.'], characterPressure: ['N’Dala wants the convoy warned.', 'Mori needs a route the damaged ship can survive.', 'Cross argues that attention divided between strangers may kill everyone.'], payoff: 'The escape demonstrates whether Act I accountability changes Vale when the endangered lives are not his crew.' },
  { beat: 10, title: 'The Palace of New Flesh', playerQuestion: 'When two people remember being the same survivor, who owns the name, the body and the choice to continue?', revealLadder: ['Cirene performs an impossible cure.', 'The recovered patient still sleeps while another version greets the family.', 'Forensics proves memories continue inside new bodies.', 'No claimant is empty, but Cirene concealed the multiplication inside the word treatment.'], characterPressure: ['Corelli refuses to equate classification with worth.', 'Morozova separates Cirene’s deception from the copies’ personhood.', 'Cirene argues that human grammar is less real than continued experience.'], payoff: 'Vale defines who returns to the Ithaca, creating a personal and political consequence that survives the ark.' },
  { beat: 11, title: 'The Captain’s Bargain', playerQuestion: 'Can Vale accept healing and alliance without surrendering the painful memories that make accountability possible?', revealLadder: ['Cirene knows an unrecorded memory of Elara.', 'The Gate left predictive living structure inside Vale.', 'Every comforting account subtly rewrites his active neural pattern.', 'Cirene offers genuine protection in exchange for the map between those memories.'], characterPressure: ['Cirene sees pain as a treatable prison.', 'Morozova treats inconvenient detail as an identity anchor.', 'Vale must distinguish refusing control from refusing help.'], payoff: 'Alliance, refusal or theft determines whether Cirene becomes witness, adversary or uneasy partner.' },
  { beat: 12, title: 'A Year Outside Time', playerQuestion: 'What reason can Vale give for leaving a refuge that has saved the crew when home has already survived another year without them?', revealLadder: ['The refit gives the crew ordinary life again.', 'Different companions privately admit what they would lose by leaving.', 'An external carrier proves thirteen months passed in forty-seven local days.', 'Only three capabilities can be restored before departure.'], characterPressure: ['Corelli asks for a humane reason stronger than longing.', 'Cross discovers obedience is not the only form of purpose.', 'Morozova insists relief must not become another silence.'], payoff: 'The ship leaves materially transformed and the crew’s chosen or compelled consent defines the next descent.' },
  { beat: 13, title: 'The Road Through the Dead', playerQuestion: 'How much life can Vale ask the crew to surrender temporarily in order to make the dead admit the ship?', revealLadder: ['The Archive destroys living visitors.', 'Cirene’s living repairs refuse shutdown.', 'The crew has ninety-four seconds of biological reserve.', 'A Warden pauses on every sleeping mind before accepting the deception.'], characterPressure: ['Mori must kill repairs she has come to value.', 'Corelli translates stealth into bodily risk.', 'Morozova warns that fear itself is detectable intention.'], payoff: 'The Ithaca enters as a corpse and wakes among records that contradict the official Gate history.' },
  { beat: 14, title: 'Voices in the Archive', playerQuestion: 'Can proof that Vale was deceived expand responsibility without becoming a machine for personal absolution?', revealLadder: ['Four records share forged timestamps.', 'The sanctuary signal predates the attack.', 'Admiral Sorren removed it from Vale’s packet.', 'Sorren admits deception but refuses to erase Vale’s unasked second question.'], characterPressure: ['Morozova names intelligence editing as authored permission.', 'Sorren frames concealment as strategic necessity.', 'Vale must preserve a truth that incriminates more people without excluding himself.'], payoff: 'The player controls which account survives into Earth’s eventual trial and the Tidefather’s judgment.' },
  { beat: 15, title: 'The Unburied Signal', playerQuestion: 'Does preservation remain mercy when a dead crew member survives only as a weapon that repeatedly overwrites her refusal?', revealLadder: ['A drone transmits Rao’s name.', 'Her emergency image was loaded without consent.', 'Fire control overwrites autobiographical memory.', 'Rao asks for one decision that belongs entirely to her.'], characterPressure: ['ELIAS can preserve data but not restore the former person.', 'Corelli makes ownership more important than quantity of memory.', 'Vale must issue an order whose moral purpose is to end his authority.'], payoff: 'Rao is freed, preserved aboard or allowed to end, defining whether command can honour refusal after death.' },
  { beat: 16, title: 'The Mother’s Message', playerQuestion: 'When home finally speaks, can Vale hear Elara’s uncertainty without converting her grief into another reason to obey him?', revealLadder: ['A damaged human carrier addresses Vale.', 'His mother died still expecting his return.', 'Earth now teaches the Gate as victory and atrocity.', 'Elara asks which version of her father is coming home.'], characterPressure: ['N’Dala protects uncertainty in the reconstruction.', 'Morozova connects truth at home to truth aboard.', 'Elara refuses to function as a passive symbol of return.'], payoff: 'The player decides whether the crew hears Elara’s actual challenge, only strategic facts, or nothing.' },
  { beat: 17, title: 'The Prophet of Probability', playerQuestion: 'Can Vale accept a real route home when its highest-survival futures all require him to stop treating command as indispensability?', revealLadder: ['Three hazards can form one route.', 'The living sun is fuel that must not be consumed.', 'Earth is not directly reachable from the Archive.', 'TIRESIAS identifies Vale’s command style as the unstable variable.'], characterPressure: ['TIRESIAS treats leadership as a probability term.', 'Morozova accepts the route but not automatic command.', 'Vale must distinguish scepticism of prediction from defence of his own authority.'], payoff: 'Act II ends with a concrete road into the Choir and a warning that makes character change a survival mechanic.' },
  {beat:18,title:'The Choir in the Dark',playerQuestion:'Can the crew protect itself from a signal that speaks in true needs rather than obvious lies?',revealLadder:['Pilgrim ships approach willingly.','Every officer hears a different promise.','The route exists inside one temptation band.','Vale alone can stabilise the carrier.'],characterPressure:['N’Dala treats listening as diagnosis.','Cross voluntarily surrenders weapons control.','Morozova refuses to let tactical isolation become renewed secrecy.'],payoff:'The filter preserves a route but leaves each companion remembering what the Choir promised.'},
  {beat:19,title:'The Silent Passage',playerQuestion:'Can Vale distinguish damaged reality from perfect reassurance when nobody else can correct him?',revealLadder:['The real interface looks broken.','False controls know Vale’s personal history.','Physical inertia exposes the counterfeit displays.','Useful route facts survive after the promise is quarantined.'],characterPressure:['Vale navigates without crew affirmation.','The Choir weaponises his need for forgiveness.','Morozova demands the unrecorded part after reconnection.'],payoff:'Vale extracts the route and admits that recognising a false Elara did not stop him asking for absolution.'},
  {beat:20,title:'The Twin Terrors',playerQuestion:'Who should bear a certain local danger when avoiding it creates a smaller chance of losing everyone?',revealLadder:['Charybdis can take the entire ship.','Scylla can reach six exposed decks.','The corridor exists only as a moving power balance.','Scylla takes six people during escape.'],characterPressure:['Cross prefers a defensible certain risk.','Morozova names who bears that risk.','Mori refuses to let the ship vote as one body.'],payoff:'The Ithaca survives the boss passage but six specific signals remain inside Scylla.'},
  {beat:21,title:'The Six Taken',playerQuestion:'How long should the ship remain exposed when every additional rescue has a name and a voice?',revealLadder:['All six captives are alive.','They can hear the command discussion.','Each tether pulse increases intercept risk.','Withdrawal makes any remaining loss an explicit decision.'],characterPressure:['Corelli keeps strategy audible to its subjects.','Cross can hold but not erase the closing threat.','Vale must record either a returned name or a reason for stopping.'],payoff:'The exact rescued and abandoned crew persist as the emotional debt carried toward Helios.'},
  {beat:22,title:'The Living Sun',playerQuestion:'Can the crew understand an alien ecology deeply enough to treat abundant energy as life before scarcity makes that understanding expensive?',revealLadder:['Solar shapes move like weather.','Population changes reveal birth and feeding.','Shepherd forms protect smaller migrations.','A slow non-lethal recharge exists beside a devastating fast route.'],characterPressure:['Morozova demands causal proof before extraction.','Mori names the engineering cost of restraint.','Corelli insists the prohibition publish its human burden.'],payoff:'Vale issues a no-harvest order after the player has seen both the life and the cost of leaving it untouched.'},
  {beat:23,title:'The Hunger Mutiny',playerQuestion:'Who owns the crime when starving people knowingly take a life after command makes the ethical burden unequal across the ship?',revealLadder:['Cold and clinic deaths make the six-day wait personal.','A lower-deck coalition captures one grazer.','The first extraction kills it before control returns.','Forty-one people share the breach and reject a convenient lone villain.'],characterPressure:['Cross defends the boundary of lawful force.','Corelli refuses to erase desperation from culpability.','Morozova includes unequal suffering in the command record.'],payoff:'The player cannot undo the death, but determines further harvest, human losses and how responsibility enters the record.'},
  {beat:24,title:'Judgment of the Star',playerQuestion:'Can Vale survive two justified accusers without treating either grieving civilisation as another target to be destroyed?',revealLadder:['Helios recognises one consumed child-form.','The Tidefather arrives behind the ship.','A living nursery lies inside the firing solution.','Rescued specialists create the only viable path through the corona.'],characterPressure:['N’Dala translates grief without softening judgment.','Cross can open a corridor but not make its targets innocent.','Morozova makes protecting the nursery a material condition of accountability.'],payoff:'The Ithaca escapes without striking the nursery, but loses its accumulated power and enters the drive crisis as a crippled core.'},
  {beat:25,title:'The Last Companion',playerQuestion:'When one certain death is required, can command make the choice fully visible and preserve the relationship instead of converting it into heroic abstraction?',revealLadder:['Remote control is impossible.','Every qualified companion volunteers for a distinct reason.','The assigned person cannot survive the second cycle.','Ship stability and the final human record compete for power.'],characterPressure:['Corelli refuses the euphemism of risk.','Morozova demands no hidden selection formula.','Each companion’s last words reflect the trust Vale actually earned.'],payoff:'One named core companion dies, the crew mourns before moving on, and an impossible Earth-like horizon appears beyond the cracked window.'},
  {beat:26,title:'The Island at the End of Time',playerQuestion:'Can Vale distinguish a home built from everything he remembers from a living home whose people retain the right to surprise and reject him?',revealLadder:['The shore reproduces private childhood detail.','Physical tests expose repeatable loops.','The child Elara cannot answer her adult message.','Calypso reveals that years pass outside and offers an unchanging life.'],characterPressure:['Calypso treats maintained comfort as a legitimate form of reality.','The dead companion’s record tests whether Vale will improve another person’s ending.','Adult Elara remains powerful precisely because the simulation cannot control her answer.'],payoff:'Vale proves paradise is a reconstruction and chooses how long to remain before demanding an exit.'},
  {beat:27,title:'The Refusal of Paradise',playerQuestion:'If every memory can be copied perfectly, can Vale define identity through obligations to people and consequences that exist beyond his control?',revealLadder:['Calypso names the exact external years lost.','The maze offers true memories with comforting false interpretations.','Another person’s unresolved voice opens an outward path.','Calypso confirms that a second autonomous Vale will remain.'],characterPressure:['Vale must refuse ownership of the dead companion’s meaning.','Calypso argues that destroying the copy would repeat the violence of ownership.','Elara’s uncertainty becomes the strongest evidence that the real world remains alive.'],payoff:'Vale reaches the real Ithaca, while the player determines the moral and political terms under which the second Vale begins.'},
  {beat:28,title:'The Hospitality Test',playerQuestion:'Can Vale tell strangers a coherent story that includes the evidence most damaging to him when their safety will depend on believing it?',revealLadder:['Phaeacian law grants shelter before judgment.','Memory bands expose the verified campaign record.','Each framing changes armed escort commitment but not sanctuary.','The Tidefather forces hospitality to become material risk.'],characterPressure:['Nausica separates care for the guest from acquittal.','A surviving companion can contradict Vale’s arrangement of the voyage.','The Tidefather treats every sheltering ship as an extension of the original crime.'],payoff:'The convoy carries Vale home, preserves its own testimony and survives only if the Ithaca defends the strangers who defended it.'},
  {beat:29,title:'The Child of the Absent Captain',playerQuestion:'Can Elara distinguish a returned father from the political uses of his identity before longing or fear decides for her?',revealLadder:['Earth receives a credible return signal.','Three occupying factions benefit from different versions of Vale.','Independent dates expose a pre-planned seizure.','The most credible record is the one that incriminates its own author.'],characterPressure:['Elara refuses to begin with memory.','Nausica offers witness without endorsement.','Earth demands inheritance before relationship.'],payoff:'Elara forms an evidence-based assessment and escapes the cordon as a playable protagonist with her own ethics.'},
  {beat:30,title:'The Stranger at His Own Door',playerQuestion:'When private habit can prove continuity but not trust, what authority should recognition restore to a changed person?',revealLadder:['Automated identity is compromised.','Elara’s evidence opens physical routes.','An air-gapped ELIAS fragment recognizes embodied fear.','Sixteen height marks reveal the life Vale did not return to.'],characterPressure:['ELIAS refuses to turn recognition into judgment.','Elara distinguishes access from ownership.','Vale must face an adult who can withhold his imagined home.'],payoff:'The reunion determines whether Elara trusts, opposes or conditionally admits Vale to the public trial.'},
  {beat:31,title:'The Trial of the Captain',playerQuestion:'Can Earth authenticate Vale, expose the full crime and preserve the witnesses while refusing to let emergency victory become acquittal?',revealLadder:['The chair identifies continuity through scars and contradiction.','Calypso proves identity can exist twice.','The Tide Gate is revealed as a gestational civilization.','The Host attacks the public record before Earth’s weapons.'],characterPressure:['Elara separates identity from authority.','A living crew witness holds deception beside voluntary action.','The Tidefather makes the dead perceptible without making vengeance innocent.'],payoff:'The crime becomes public and survives the vanguard, making atonement possible before the final siege.'},
  {beat:32,title:'The Last God at the Gate',playerQuestion:'After tactical victory, which power, witness and relationship must Vale surrender to end the cycle rather than merely win it?',revealLadder:['Protected witnesses constrain the orbital battle.','Elara makes Earth’s defence answerable.','Shared memory holds both crimes without collapse.','Five endings expose different costs and only campaign-earned paths remain available.'],characterPressure:['Vale confronts home without entitlement.','Elara controls succession rather than receiving it.','The Tidefather must choose whether grief can exist without possession.'],payoff:'The deterministic campaign resolves through vengeance, atonement, reconciliation, exile or succession with a bespoke epilogue.'},
] as const

export const ACT_THREE_CHARACTER_ARCS = {
  'alexander-vale':['admits the Choir found a real need','names every person left inside Scylla','makes the Helios prohibition visible before scarcity','must personally assign and record one certain death'],
  'helen-morozova':['prevents tactical isolation from restoring secrecy','asks which compartments bear the chosen passage','makes unequal suffering part of mutiny causality','demands a transparent companion choice with no moral euphemism'],
  'gabriel-cross':['surrenders weapon control when temptation targets purpose','holds a route he knows will expose named decks','distinguishes desperation from permission during mutiny','offers himself without turning loyalty into automatic selection'],
  'lena-mori':['translates false navigation into physical ship truth','makes power allocation expose who bears danger','names the exact engineering price of ethical recharge','faces a drive that can move only by consuming one companion'],
  'isabella-corelli':['keeps the rescue discussion audible to its subjects','carries both returned and abandoned names','holds alien life and preventable clinic death in the same record','refuses to let certain death be described as medical risk'],
  'kiara-ndala':['diagnoses private temptation without shaming it','preserves the useful route inside an adversarial signal','gives Helios a voice without making it human','keeps the final channel alive only if the player spends stability'],
  elias:['helps quarantine reassurance without deleting need','preserves the rescue ledger without abbreviation','remembers how command secrecy shaped earlier mutiny','can become the last witness or preserve the chosen companion’s record'],
} as const

export const ACT_THREE_CODA_CHARACTER_ARCS = {
  'alexander-vale':['discovers that perfect memory cannot produce another person’s freedom','defines identity through unfinished obligations rather than originality','narrates the voyage without controlling what strangers preserve'],
  'helen-morozova':['may survive as the first crew voice to answer Vale after paradise','judges whether the returned captain still carries contradiction','supports or contests the account placed before the Phaeacians'],
  'gabriel-cross':['may survive to distinguish defensive context from absolution','helps a crippled ship accept protection from strangers','defends hospitality as an obligation rather than a tactical bargain'],
  'lena-mori':['may survive to verify that the real Ithaca remains damaged','refuses a simulated ship repaired by forgetting its people','makes the convoy’s protection mechanically costly and visible'],
  'isabella-corelli':['may survive to reject resurrection made from Vale’s need','keeps the copy’s emerging consciousness inside the moral record','asks whether testimony names the people who paid for survival'],
  'kiara-ndala':['may survive to distinguish Calypso’s care from consent','recognises the copy as a new voice rather than stored equipment','translates Phaeacian hospitality and the Tidefather’s threat without softening either'],
  elias:['remains the continuity witness Calypso cannot replace with perfect memory','treats two Vales as a personhood problem rather than an authentication error','preserves the account that later allows him to recognise Vale at home'],
} as const

export const ACT_FOUR_CHARACTER_ARCS = {
  'alexander-vale':['returns as a contested person rather than a restored office','accepts recognition without treating it as authority','places corrupted intelligence beside his voluntary firing order','chooses which power or future he will no longer control'],
  'helen-morozova':['if alive, contradicts Vale inside the public witness record','makes authentication and acquittal separate scientific claims','preserves both conspiracy evidence and command responsibility','supports a peace only if its records remain independently held'],
  'gabriel-cross':['if alive, defends the witnesses instead of the heroic legend','holds the citadel without demanding emergency permanence','accepts restraint toward protected enemy memory systems','allows civilian succession to replace wartime loyalty'],
  'lena-mori':['if alive, verifies the damaged ship rather than a simulated repair','turns Earth repair into an explicit material gift','keeps the final battle objective distinct from annihilation','makes the Ithaca a sanctuary seed, exile vessel or relinquished inheritance'],
  'isabella-corelli':['if alive, keeps the dead companion a record rather than a resurrected convenience','makes civilian shelter independent from weapons','treats Host grief as context without granting permission','measures the ending by which lives retain their own voice'],
  'kiara-ndala':['if alive, authenticates independent Phaeacian testimony','translates the cradle memory without reducing it to human language','keeps the shared-memory bridge open to contradiction','records the peace in more than one civilization’s custody'],
  elias:['recognizes a private embodied gesture through an air-gapped fragment','refuses to turn authentication into trust','preserves Elara’s missing years beneath the command dais','survives as witness to succession rather than guarantor of Vale’s legend'],
} as const

export const CHARACTER_ARCS = {
  'alexander-vale': ['longing for Elara', 'secrecy versus accountability', 'identity as weapon or confession', 'command responsibility for mutiny'],
  'helen-morozova': ['scientific doubt', 'moral opposition', 'recognition of Eidolon grief', 'trust as a material survival system'],
  'gabriel-cross': ['loyal tactical confidence', 'legend as protection', 'defense of the Gate order', 'order after conspiracy'],
  'lena-mori': ['ship damage as human cost', 'sacrifice as casualty', 'wonder in Aeolia', 'engineering truth against rumour'],
  'isabella-corelli': ['triage of named lives', 'ambiguous consent in Eirenai', 'shared sanctuary trauma', 'fear as context rather than excuse'],
  'kiara-ndala': ['first alien voice', 'translation of grief', 'Aeolian hospitality', 'the cost of silencing communication'],
  elias: ['witness to the younger Vale', 'machine asked to lie', 'guardian of the forbidden boundary', 'demand that Vale judge himself'],
} as const

export const ACT_TWO_CHARACTER_ARCS = {
  'alexander-vale': ['spends safety on strangers or protects only his ship', 'must define personhood without a military rule', 'resists or accepts a kinder rewritten self', 'asks rather than assumes who will continue home'],
  'helen-morozova': ['tests whether Act I accountability changed Vale', 'separates Cirene’s deception from the copies’ worth', 'anchors Vale to inconvenient truth', 'protects recovery without letting refuge conceal time'],
  'gabriel-cross': ['tactical survival conflicts with convoy rescue', 'order cannot solve duplicate identity', 'the theft path makes loyalty active complicity', 'discovers discipline and exhaustion were entangled'],
  'lena-mori': ['turns a harbour route into human and mechanical cost', 'watches living technology repair without permission language', 'negotiates boundaries with Cirene’s scaffolds', 'admits competence does not mean wanting to leave'],
  'isabella-corelli': ['receives the survivors of Vale’s harbour choice', 'defends every conscious claimant from becoming equipment', 'names rest as a real form of survival', 'demands a reason for home stronger than Vale’s longing'],
  'kiara-ndala': ['makes strangers inside the convoy audible', 'tracks the semantic concealment inside continuity', 'keeps an external channel alive through sanctuary', 'reveals the year relief allowed to pass'],
  elias: ['carries Act I choices into the harbour record', 'audits bodies without claiming to measure souls', 'can enable the theft that turns Cirene hostile', 'preserves the voyage log across altered crew and ship'],
} as const
