export interface ExperienceMinigame {
  id: string
  beat: number
  goal: string
  input: string
  stakes: string
  feedback: readonly string[]
  narrativeFunction: string
  consequence: string
  targetSeconds: readonly [number, number]
}

export interface ExperienceBeat {
  beat: number
  title: string
  playerQuestion: string
  revealLadder: readonly string[]
  characterPressure: readonly string[]
  payoff: string
}

export const EXPERIENCE_MINIGAMES: readonly ExperienceMinigame[] = [
  { id: 'emergency-routing', beat: 2, goal: 'Keep life support online while distributing eight scarce reactor-load units.', input: 'Toggle named ship systems and commit a legal power allocation.', stakes: 'Every powered system changes what the Ithaca can save in the next scene.', feedback: ['load counter', 'energized system nodes', 'locked over-capacity choices'], narrativeFunction: 'Turns the scale of the disaster into the player’s first material command decision.', consequence: 'Selected systems are repaired; omitted engines cost hull and omitted medical power narrows recovery.', targetSeconds: [35, 90] },
  { id: 'triage', beat: 2, goal: 'Choose two of four named casualties for the remaining surgical bays.', input: 'Inspect the medical and personal consequence on each patient card, then assign two.', stakes: 'There is no optimal answer and every unselected patient remains part of the casualty record.', feedback: ['selection state', 'live assignment count', 'patient vitals'], narrativeFunction: 'Makes the Gate catastrophe personal before the crew asks Vale to account for it.', consequence: 'Named survivors, restored capabilities and Corelli’s trust persist in campaign state.', targetSeconds: [45, 120] },
  { id: 'memory-fragments', beat: 3, goal: 'Rebuild Lieutenant Sato’s autobiographical memory from earliest fragment to latest.', input: 'Select four visual memory fragments in causal order and test the chain.', stakes: 'Failure shows identity continuing to fracture, while success proves the garden is altering consent.', feedback: ['filled memory chain', 'error shake', 'fragment lockout'], narrativeFunction: 'Lets the player experience memory loss before judging crew who want to remain.', consequence: 'The restored testimony becomes evidence and changes Corelli’s confidence in Vale.', targetSeconds: [35, 100] },
  { id: 'shuttle-pursuit', beat: 3, goal: 'Thread the Ithaca through habitat rings before the deserter shuttle docks.', input: 'Move between three lanes with keyboard or on-screen flight controls.', stakes: 'Collisions damage the ship and failure leaves the departing crew in Eirenai.', feedback: ['range progress', 'live hull meter', 'moving obstacle field'], narrativeFunction: 'Converts Vale’s decision to retrieve the deserters into an uncomfortable physical pursuit.', consequence: 'The crew is recovered by force or left behind, and the chase damage persists.', targetSeconds: [70, 130] },
  { id: 'blind-the-eye', beat: 4, goal: 'Align four stolen calibration rings with ARGUS-1’s null harmonic.', input: 'Rotate each phase ring and inject a test harmonic before detection reaches four attempts.', stakes: 'Every failed test makes the escape combat harder rather than stopping the story.', feedback: ['matching-harmonic count', 'detection-risk meter', 'animated sensor reticle'], narrativeFunction: 'Makes the Cyclops escape depend on observation and cunning before weapons.', consequence: 'Success blinds the cutter network; failure awakens an extra combat target and damages shields.', targetSeconds: [45, 120] },
  { id: 'transponder-cipher', beat: 5, goal: 'Mask four identity layers before ARGUS finishes its interstellar broadcast.', input: 'Rotate five-phase carrier dials, using echo-correlation strength to find each null.', stakes: 'A weak cipher adds pursuit pressure before Vale decides what name to transmit.', feedback: ['per-layer echo correlation', 'cyan null lock', 'injection count'], narrativeFunction: 'Places a practical disguise in Vale’s hands immediately before the moral choice to use it.', consequence: 'A traceable carrier increases pursuit; the later identity choice changes relationships and the Tidefather’s greeting.', targetSeconds: [40, 110] },
  { id: 'sacrifice-system', beat: 6, goal: 'Evacuate and permanently sever one Gate-altered system so the emergency jump can carry the ship.', input: 'Compare five ship systems, hear the responsible officer, arm the choice, then confirm severance.', stakes: 'The selected system reaches zero integrity and its loss is named in the immediate aftermath.', feedback: ['ship cutaway highlight', 'crew witness response', 'two-stage irreversible confirmation'], narrativeFunction: 'Makes escape from the Tidefather cost a piece of the shared home rather than an abstract resource.', consequence: 'Weapons, shields, medical, sensors or communications is destroyed and the ship gains a matching scar.', targetSeconds: [55, 150] },
  { id: 'phase-current', beat: 7, goal: 'Stabilize four magnetic vanes around a captured spatial current.', input: 'Advance or retard each six-phase vane according to its visible drift cue, then test containment.', stakes: 'Repeated failed tests make the sphere volatile and increase the pursuer’s trace.', feedback: ['advance/retard cue', 'stable-vane count', 'vessel-stress meter'], narrativeFunction: 'Turns Aeolia’s gift into something the crew must understand and tend rather than simply receive.', consequence: 'The Ithaca gains the Aeolian sphere; unstable containment adds pursuit pressure.', targetSeconds: [45, 120] },
  { id: 'storm-flight', beat: 7, goal: 'Keep the contained current aligned while flying through the Aeolian upper storm.', input: 'Move between three lanes to pass through incoming luminous wind gates.', stakes: 'Missed gates destabilize the sphere and can damage both hull and engines.', feedback: ['visible approaching gates', 'course progress', 'sphere-stability meter'], narrativeFunction: 'Lets the hopeful sanctuary beat end with exhilarating action and proves the gift under pressure.', consequence: 'A clean test repairs hull; a poor test damages the Ithaca before the sphere voyage.', targetSeconds: [70, 130] },
  { id: 'access-log', beat: 8, goal: 'Reconstruct the causal chain that turned a rumour into the sphere’s manual release.', input: 'Read five untimed fragments, order them by cause and dependency, clear freely, then verify.', stakes: 'Only the evidence can distinguish a frightened conspiracy from one convenient scapegoat.', feedback: ['ordered causal chain', 'correct-link count', 'attempt counter'], narrativeFunction: 'Requires the player to understand why the mutiny happened before passing judgment on it.', consequence: 'Complete or partial evidence changes what Vale knows when choosing punishment, forgiveness or responsibility.', targetSeconds: [60, 150] },
] as const

export const EXPERIENCE_BEATS: readonly ExperienceBeat[] = [
  { beat: 1, title: 'The Burning of the Tide Gate', playerQuestion: 'What did Vale know before he fired, and why did he fire anyway?', revealLadder: ['The Gate is the last military obstacle.', 'Its internal signals resemble cell division.', 'The screen falls and eight million signals stop.', 'Morozova identifies a sanctuary only after the irreversible order.'], characterPressure: ['Vale wants to reach Elara.', 'Cross sees the last firing window.', 'Morozova asks for certainty the battle cannot provide.'], payoff: 'Victory becomes the crime that powers every later pursuit.' },
  { beat: 2, title: 'The Wrong Stars', playerQuestion: 'Can Vale ask the crew to trust him while deciding who and what survives?', revealLadder: ['The constellations are unknown.', 'The drive remains fused with alien matter.', 'Named casualties expose the cost deck by deck.', 'The crew asks for the record Vale could still seal.'], characterPressure: ['Corelli makes strategy answer to individual lives.', 'Mori translates damage into future limitations.', 'Morozova makes secrecy a second decision.'], payoff: 'The player establishes whether this voyage begins with public truth or managed silence.' },
  { beat: 3, title: 'The Garden of Forgetting', playerQuestion: 'Is bringing people home still rescue when they no longer choose the journey?', revealLadder: ['A human refuge offers free sanctuary.', 'Calm is produced by suppressing trauma.', 'Memory reconstruction reveals consent is being altered.', 'Twenty-three crew leave despite understanding the choice.'], characterPressure: ['Corelli refuses a clean diagnosis of free choice.', 'N’Dala carries the deserters’ plea.', 'Vale confronts the difference between mission and ownership.'], payoff: 'The player pursues the shuttle or accepts a permanent loss of crew.' },
  { beat: 4, title: 'The One-Eyed Fortress', playerQuestion: 'Can the crew escape an ancient machine by proving they are more than useful material?', revealLadder: ['The moon appears abandoned and fuel-rich.', 'Its doors close after entry.', 'ARGUS classifies life as contamination.', 'Its own recovery law can be turned against its central eye.'], characterPressure: ['Mori needs the fuel but sees the ship being peeled apart.', 'Morozova recognizes the exploitable rule.', 'Vale must argue for personhood to a system without empathy.'], payoff: 'Cunning opens the exhaust route, but ARGUS broadcasts the escape.' },
  { beat: 5, title: 'The Captain Gives His Name', playerQuestion: 'Is Vale’s identity a responsibility to own, a weapon to use, or a vulnerability to hide?', revealLadder: ['ARGUS is broadcasting a partial record.', 'ELIAS can forge the identity layers.', 'Cross argues that reputation is armor.', 'A response returns faster than light should allow.'], characterPressure: ['ELIAS remembers Vale before command made him secretive.', 'Morozova frames naming as ownership of consequence.', 'Cross wants a legend the enemy will fear.'], payoff: 'The chosen identity directly shapes pursuit and the Tidefather’s first words.' },
  { beat: 6, title: 'The First Wrath', playerQuestion: 'What can Vale say after experiencing the sanctuary dead as lives rather than telemetry?', revealLadder: ['Thirteen seconds vanish from every clock.', 'The Tidefather knows Vale beneath any false identity.', 'The crew experiences the sanctuary’s final moments.', 'The pursuer could kill the Ithaca but chooses recognition and loss.'], characterPressure: ['Cross insists weapon and sanctuary can both be true.', 'Helen asks whether recognition must change command.', 'Mori refuses to call a human workplace disposable ballast.'], payoff: 'Survival requires permanently sacrificing one part of the ship.' },
  { beat: 7, title: 'The Keeper of Winds', playerQuestion: 'Can Vale earn a route home that only works if his crew trusts a sealed boundary?', revealLadder: ['Aeolia offers unconditional immediate shelter.', 'Her people already know the Eidolon accusation.', 'The spatial current can cross years of distance.', 'The sphere projects whatever the traveller most longs to see.'], characterPressure: ['Aeolia demands truth without the grammar of victory.', 'Morozova sees trust as the real containment field.', 'N’Dala warns that an image of home will become a promise.'], payoff: 'The crew earns and tests the sphere, carrying fragile hope aboard.' },
  { beat: 8, title: 'The Forbidden Sphere', playerQuestion: 'Who is responsible when command secrecy turns exhausted people into conspirators?', revealLadder: ['Four incompatible crew perspectives expose the same trust wound.', 'Familiar stars and Elara’s old recording make home feel immediate.', 'Someone opens the sphere using Vale’s authority.', 'The evidence begins with rumour and ends with a frightened human choice.'], characterPressure: ['Cross protects order.', 'Corelli protects frightened people from becoming targets.', 'ELIAS asks whether Vale can include himself in the sentence.'], payoff: 'The route home is lost and the player defines how this command answers its first mutiny.' },
] as const

export const CHARACTER_ARCS = {
  'alexander-vale': ['longing for Elara', 'secrecy versus accountability', 'identity as weapon or confession', 'command responsibility for mutiny'],
  'helen-morozova': ['scientific doubt', 'moral opposition', 'recognition of Eidolon grief', 'trust as a material survival system'],
  'gabriel-cross': ['loyal tactical confidence', 'legend as protection', 'defense of the Gate order', 'order after conspiracy'],
  'lena-mori': ['ship damage as human cost', 'sacrifice as casualty', 'wonder in Aeolia', 'engineering truth against rumour'],
  'isabella-corelli': ['triage of named lives', 'ambiguous consent in Eirenai', 'shared sanctuary trauma', 'fear as context rather than excuse'],
  'kiara-ndala': ['first alien voice', 'translation of grief', 'Aeolian hospitality', 'the cost of silencing communication'],
  elias: ['witness to the younger Vale', 'machine asked to lie', 'guardian of the forbidden boundary', 'demand that Vale judge himself'],
} as const
